package-lock.json, package.json, ui/index_template.html
Referenced https://github.com/wowsims/sod/pull/399
=> Set @protobuf-ts to version 2.9.1 and remove Pako.js from CDN

package-lock.json, ui/core/components/character_stats.tsx
On branch fix_ts_errors
modified:   package-lock.json
modified:   ui/core/components/character_stats.tsx
=> Fixed error in Bootstrap API call

proto/common.proto, sim/core/consumes.go, ui/core/components/individual_sim_ui/consumes_picker.ts, ui/core/components/inputs/consumables.ts, ui/death_knight/blood/presets.ts, ui/death_knight/frost/presets.ts, ui/druid/balance/presets.ts, ui/druid/restoration/presets.ts, ui/hunter/marksmanship/presets.ts, ui/paladin/holy/presets.ts, ui/paladin/protection/presets.ts, ui/priest/discipline/presets.ts, ui/priest/holy/presets.ts, ui/priest/shadow/presets.ts, ui/shaman/elemental/presets.ts, ui/warlock/affliction/presets.ts, ui/warlock/demonology/presets.ts, ui/warlock/destruction/presets.ts, ui/warrior/arms/presets.ts, ui/warrior/fury/presets.ts, ui/warrior/protection/presets.ts
Added them, removed some old stuff that has replacements, and updated presets to be able to compile
=> Add all Potions, Flasks and Elixirs

ui/scss/core/components/detailed_results/_timeline.scss
Added:
- Bottom border to timeline aura.
- Added opacity to cast and spell travel time.
=> Added borders and colors to timeline

sim/common/cata/enchant_effects.go, sim/core/aura.go, sim/core/aura_helpers.go
Use helper proc trigger methods when possible and fix some wrong ids
=> Enchants cleanup

sim/core/flags.go, sim/core/spell_mod.go, sim/core/spell_resistances.go, sim/core/spell_result.go, sim/hunter/survival/TestSV.results, ui/core/proto_utils/logs_parser.tsx
- Fixed partial resists to properly show in logs
- Add Bonus hit rating Spell Mod
- Add Dot number of ticks Spell Mod
- Fix spellPower double dip
=> Partial Resists log fixes and new Spell mods

proto/common.proto, sim/core/character.go, sim/core/database.go, sim/shaman/shaman.go
=> implement armor specialization bonuses

sim/core/aura.go, sim/core/aura_helpers.go, sim/core/metrics_aggregator.go, sim/core/racials.go, sim/core/spell.go, sim/death_knight/diseases.go, sim/death_knight/pestilence.go, sim/death_knight/talents_unholy.go
Add a callback executed before onApplyEffects for modyfing spell data before casts and after for effects like Contagion and Ebon Plaguebringer
=> Add aura OnApplyEffects callback

sim/priest/mind_spike.go, sim/priest/shadow/TestShadow.results, sim/priest/talents.go
=> [Shadow] Fix potential panic and Archangel GCD

sim/core/dot.go, sim/core/spell_mod.go, sim/priest/talents.go
* Should now properly allow tick mods to change hasted spells tick count
=> [Core] Refactor DoT haste handling

ui/core/party.ts
=> [UI] Fix gear swap

sim/core/debuffs.go, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results
=> [Debuffs] Fixup curse of elements

sim/warrior/stances.go
Updated in 4.0.1 to 25 (https://www.wowhead.com/cata/spell=12678/stance-mastery)
=> [warrior] update stance mastery

sim/shaman/enhancement/TestEnhancement.results, sim/shaman/shaman.go, ui/shaman/enhancement/sim.ts
changed agi scaling from 1 agi = 2.4 ap to 1 agi = 2 ap
Added strength scaling, 1 str = 1 ap.
=> updating how enhance scales with agi and strength

sim/warrior/items.go
Fixed the War T11 4P bonus Rage of Ages crashing sim
=> [Warrior] Bug fix item Rage of Ages

sim/warrior/arms/arms.go
Strikes of Opportunity was glancing.  Fixed to no longer glance.
=> [Warrior] Fix Strikes of Opportunity

sim/warrior/heroic_leap.go, sim/warrior/warrior.go
=> [Warrior] Added Heroic leap

sim/druid/druid.go, sim/druid/thrash.go
first attempt at contributing, be gentle...
=> implementing druid Thrash

ui/core/components/inputs/buffs_debuffs.ts, ui/core/player_classes/druid.ts, ui/core/player_classes/hunter.ts, ui/core/player_classes/mage.ts, ui/core/player_classes/paladin.ts, ui/core/player_classes/priest.ts, ui/core/player_classes/rogue.ts, ui/core/player_classes/shaman.ts, ui/core/player_classes/warlock.ts, ui/core/player_classes/warrior.ts, ui/raid/raid_picker.ts, ui/raid/raid_stats.ts, ui/raid/raid_tab.ts
Make the raid sim page show. Current issue is talents are not loaded for players and when edited manually are not persisted. Something must be wrong with the application of talents in players when done from the raid sim
=> Fixes for raid sim

sim/warrior/talents.go
Fixed the extra 100% damage from war academy
=> fixed war academy

proto/common.proto, sim/core/buffs.go, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/pet.go, sim/hunter/pet_abilities.go, sim/hunter/survival/TestSV.results, ui/core/components/inputs/buffs_debuffs.ts
Fixed the damage of the Hunter pets. Pet should now hit their special abilities, but they won't do damage as in wotlk as they provide only utility now.
In another PR I'll add the raid debuffs/buffs hunter pets provide
=> Hunter pets damage

ui/core/components/content_block.tsx, ui/core/components/individual_sim_ui/gem_summary.tsx, ui/core/components/individual_sim_ui/reforge_summary.tsx, ui/scss/core/components/_content_block.scss, ui/scss/core/components/individual_sim_ui/_summary_table.scss, ui/scss/shared/_bootstrap_style_overrides.scss
=> [UI] Reforge / Gem summary tweaks

sim/core/base_stats.go, sim/core/utils.go, sim/priest/holy/holy.go, ui/core/components/detailed_results/metrics_table.tsx, ui/core/components/detailed_results/player_damage.ts, ui/scss/core/components/detailed_results/_player_damage.scss
Also update a bit the results page in raid sim
=> move class base scaling to base stats

sim/warrior/arms/talents.go
https://www.wowhead.com/cata/spell=16494/impale
=> [Warrior] update impale spellmod to give crit damage bonus instead of crit rating

sim/warrior/arms/talents.go, sim/warrior/fury/talents.go, sim/warrior/items.go
Also updated the wrecking crew aura actionID to the enrage spellID that is the actual in-game proc
=> [Warrior] fix SchoolDamageDealtMultiplier to use the correct index

ui/warrior/arms/gear_sets/p1_arms_bis.gear.json
fixed missing random suffix on cloudburst ring
=> [Warrior] Fix missing random suffix on preset

sim/common/cata/enchant_effects.go, sim/priest/shadow/TestShadow.results
Lightweave embroidery:
https://www.wowhead.com/cata/spell=75170/lightweave
https://www.wowhead.com/cata/spell=75171/lightweave-embroidery
Darkglow embroidery:
https://www.wowhead.com/cata/spell=75173/darkglow
https://www.wowhead.com/cata/spell=75174/darkglow-embroidery
=> Fix tailoring cloak enchants

ui/scss/core/components/_sim_title_dropdown.scss, ui/scss/core/sim_ui/_sidebar.scss
Added a z-index and position value so the sidebar z-index was applied. (static positioning is default and doesn't apply any z-index properties)
=> [UI] Fix: Overlapping sim results over sim-type dropdown

sim/core/racials.go, sim/core/spell_result.go, sim/mage/fire/pyroblast.go, sim/mage/living_bomb.go, sim/mage/mage.go, sim/mage/talents_fire.go, ui/core/proto_utils/action_id.ts, ui/mage/fire/apls/fire.apl.json
- Refactored some parts of ignite
- Fixed Hot Streak to give proper bonuses to the Pyro
- More cleanup
=> Mage Fixes

sim/hunter/beast_mastery/beast_mastery_test.go, sim/hunter/marksmanship/TestMM.results, sim/hunter/pet_abilities.go, sim/hunter/talents.go, ui/core/components/encounter_picker.ts, ui/core/talents/hunter_pet.tsx, ui/hunter/beast_mastery/sim.ts, ui/hunter/marksmanship/apls/mm.apl.json, ui/hunter/marksmanship/apls/mm_advanced.apl.json, ui/hunter/marksmanship/sim.ts, ui/hunter/survival/sim.ts
Change tooltip text on Execute 90%
Imp Steady on Apply Effects instead of SpellHitDealt
Adjust MM APL
=> Hunter fixes

ui/core/components/importers.ts, ui/core/components/individual_sim_ui/bulk_tab.ts, ui/core/components/settings_menu.tsx, ui/core/components/stat_weights_action.ts, ui/core/components/toast.tsx, ui/core/player.ts, ui/core/sim.ts, ui/core/sim_ui.tsx, ui/core/worker_pool.ts, ui/raid/import_export.ts, ui/scss/core/sim_ui/_shared.scss, ui/scss/index.scss, ui/scss/shared/_bootstrap_style_overrides.scss, ui/scss/shared/_variables.scss
- Added Toast class based on Bootstrap's Toast
- Different variants: success, info and error
- Default delay of 3 seconds
- Updated some important success / error outputs to Toasts
=> [UI] Add toasts

ui/core/components/importers.ts
Accidentally pressed undo 1 too many times :(
=> [Importer] Add itemID resolve fix

sim/warrior/fury/glyphs.go, sim/warrior/fury/raging_blow.go, sim/warrior/protection/glyphs.go
Fixed raging blow applying crit to off hand.
Put guards on prot and fury glyphs
=> [Warrior]Fixed Raging Blow Glyph

sim/warrior/arms/talents.go
=> [Warrior] Add Talent Juggernaut

sim/common/cata/other_effects.go, sim/druid/feral/TestFeral.results, sim/priest/shadow/TestShadow.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results
Make [Tyrande's Doll](https://www.wowhead.com/cata/item=64645/tyrandes-favorite-doll) reset stored mana on sim reset.
=> Fix Tyrandes Doll reset

sim/priest/shadow/TestShadow.results, sim/priest/talents.go, sim/warrior/arms/TestArms.results, sim/warrior/arms/blood_frenzy.go, sim/warrior/stances.go, sim/warrior/warrior.go
Fixes Arms and Shadow reset problems
=> Reset fixes

sim/core/debuffs.go
On branch fix_demo
modified:   sim/core/debuffs.go
=> Fixed indexing bug with spell school for 10% damage debuffs

sim/mage/arcane_missiles.go, sim/mage/fire/pyroblast.go, sim/mage/talents_arcane.go, sim/mage/talents_fire.go
Fixed Netherwind Presence, Arcane Missiles, let Pyroblast DoT crit, and got Cata Ignite working.
=> [Mage] Cata Ignite and some misc fixes

sim/core/debuffs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/bloodworm_pet.go, sim/death_knight/summon_gargoyle.go, sim/death_knight/unholy/TestUnholy.results
=> Gargoyle and Bloodworm fixes and Acid Spit crash fix

sim/druid/moonfire.go, sim/druid/sunfire.go, sim/druid/talents.go, ui/druid/balance/sim.ts
fixed a crash with the sim due to a typo in the Sunfire registration
fixed Nature's Majesty not providing the proper amount of crit alongside UI support
added the missing call to applyGlyphs()
=> Balance druid implementation

sim/shaman/enhancement/TestEnhancement.results, sim/shaman/spirit_wolves.go
Based on stats dumped from character sheet
=> Update Spirit Wolves

ui/core/components/exporters.tsx, ui/core/components/importers.ts, ui/raid/raid_sim_ui.ts
#349 Added pako back as dependency and removed the global type setter
=> [FIX] [ISSUE 349] Add pako back as dependency

ui/core/components/gear_picker/gear_picker.tsx, ui/scss/homepage/_homepage.scss
- Fixed media query
- Fixed "Remove reforge" button
=> [FIX] homepage dropdown and reforge removal

ui/raid/raid_picker.ts, ui/raid/raid_sim_ui.ts, ui/raid/raid_stats.tsx, ui/raid/raid_tab.ts
- Fixes Raid player editor not working
- Fixes Roles not working
=> Fix raid sim crash/error

ui/core/components/base_modal.tsx, ui/core/components/filters_menu.ts, ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/importers.ts, ui/core/components/individual_sim_ui/bulk_tab.ts, ui/core/components/settings_menu.tsx, ui/core/components/stat_weights_action.ts, ui/core/talents/glyphs_picker.tsx, ui/raid/raid_picker.tsx
- Fixes player editor modals not changing tabs by reusing and updating 1 modal's contents
=> [FIX] Raid sim editor

sim/warrior/arms/TestArms.results, sim/warrior/warrior.go
Fixed base parry from str
Fixed Arms test
=> [Warrior] Fix parry from str

sim/core/buffs.go, sim/core/spell_mod.go, sim/mage/arcane_blast.go, sim/mage/arcane_missiles.go, sim/mage/mage.go, sim/mage/mana_gems.go, sim/mage/talents_arcane.go, ui/core/components/inputs/consumables.ts, ui/mage/arcane/apls/arcane.apl.json
- Fixed Clearcasting
- Fixed AB stacking on misses
- Fixed Improved Mana Gem
- Fixed PoM consuming on wrong spells
- Updated Arcane APL to a working test one
=> Arcane Mage Updates

proto/hunter.proto, sim/core/buffs.go, sim/core/debuffs.go, sim/hunter/beast_mastery/TestBM.results, sim/hunter/hunter.go, sim/hunter/marksmanship/TestMM.results, sim/hunter/pet.go, sim/hunter/pet_abilities.go, sim/hunter/pet_talents.go, sim/hunter/survival/TestSV.results, ui/core/components/inputs/buffs_debuffs.ts, ui/core/proto_utils/action_id.ts, ui/core/talents/hunter_pet.tsx
=> Small pet rehaul

sim/core/racials.go, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/shaman/enhancement/TestEnhancement.results
=> Fix Orc and Dwarf expertise racial bonus

sim/druid/feral/TestFeral.results, sim/druid/feral/rotation.go
modified:   sim/druid/feral/rotation.go
=> Swap Thrash and Mangle priority within bear-weaves

ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/sim_header.tsx, ui/core/individual_sim_ui.tsx, ui/core/launched_sims.ts, ui/core/player.ts, ui/core/proto_utils/equipped_item.ts, ui/core/proto_utils/utils.ts, ui/core/utils.ts, ui/scss/core/sim_ui/_shared.scss
- Added unlaunched sim warning
- Added `isPVPItem` fn
=> [UI] Unlaunched Sim warning & PVP cleanup

ui/core/individual_sim_ui.tsx
- Fixed typo and added contributing message
=> Add Discord link to message

sim/core/pet.go, sim/priest/shadow/TestShadow.results, sim/priest/talents.go
* Also fixup lingering pets after sim iteration
=> [Priest] Fixup sin and punishment

ui/raid/raid_picker.tsx
- Makes sure there are no empty slots in between players in a raid party
- Fixes the issue where a raid sim wouldn't finish because it crashed silently
=> [UI] Auto shift empty slots

sim/warlock/pets.go
Same technique as used by gargoyle.
=> warlock: fix broken imp GCD emulation

sim/hunter/hunter.go, sim/hunter/pet.go, sim/hunter/pet_abilities.go
=> Fix Roar of Courage

sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/items.go, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/shield_block.go
Added Prot T12 4P
Updated Tests
=> [Warrior] T12 4P

sim/common/cata/stat_bonus_cds.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
Add missing Unsolvable Riddle itemId (62463)
Fix the comments accordingly
=> Add missing Unsolvable Riddle item

sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/protection/protection.go, sim/warrior/shield_block.go, sim/warrior/talents.go, sim/warrior/warrior.go
Fixed the critical block from hold the line from being overwritten.
Update tests
=> [Warrior]Fix Prot Crit Block overwriting

sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/items.go, sim/warlock/warlock.go
Introduced in 22a7812f0cab28c7316969a6919841e75720409b
=> warlock: fix fel spark stacks not being consumed

sim/hunter/survival/TestSV.results, sim/hunter/trap_launcher.go, ui/hunter/survival/apls/aoe.apl.json
=> hunter: add trap launcher to survival aoe apl

sim/core/character.go, sim/core/professions.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results
Flat updates to Mining+Skinning, rework of Herbalism's Lifeblood.
Updates default healing crit multi to 2.0 as per https://github.com/JamminL/cata-classic-bugs/issues/958
=> Update gathering profession bonuses & default healing crit multiplier

ui/core/components/individual_sim_ui/consumes_picker.tsx
- Fixed missing consumable options
=> [UI][FIX] Add missing refs

ui/core/components/individual_sim_ui/apl_rotation_picker.ts
- Fixes Eye button not working in APL
=> [FIX][UI] Rotation button toggle

sim/core/character.go, sim/core/racials.go
=> Add gnome weapon specialization

sim/warrior/arms/TestArms.results, sim/warrior/arms/talents.go, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/rend.go
following the ongoing topic in the \#cata-warrior discord channel
=> [Warrior] update rend damage calculation, dynamic snapshot and extra mortal strike tick

sim/core/racials.go
=> implement warrior and hunter arcane torrent

sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/talents.go, ui/warrior/arms/apls/arms.apl.json
APL changes:
- adding charge and battle shout to prepull actions
- adding zerker rage & shout to the bottom prio of combat actions
- changing HS threshold to 75 rage
=> [Warrior] Fix battle trance proc and default APL

ui/core/components/individual_sim_ui/rotation_tab.tsx, ui/core/components/input.tsx, ui/core/components/saved_data_manager.tsx, ui/core/individual_sim_ui.tsx
- Allows you to reset an APL rotation
**After reset press**
=> [UI] Add APL reset button

ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/utils.ts, ui/scss/core/components/_bulk.scss, ui/scss/shared/_global.scss, ui/scss/shared/_variables.scss
- Fixes gear selector bugs
- Fixes gem selector bug
- Fixes bulk results rendering
- Optimized HTML with JSX rendering
- Add excluded tabs render prop to item modal
=> [UI] Bulk Sim

ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/utils.ts
- Fixes tabs not updating properly
- Added missing Reforge / random suffix option to Batch tab
=> [FIX] Tab switching

sim/core/consumes.go
Resolves https://github.com/wowsims/cata/issues/597
=> [Bug] Fix tazik's shocker engineering tinker

sim/common/cata/stat_bonus_procs.go, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/rogue/combat/TestCombat.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
Resolves https://github.com/wowsims/cata/issues/607
=> [Items] Add agony and torment set bonus

ui/core/components/suggest_reforges_action.tsx
Break ties for Spirit vs. Hit Reforges for hybrid casters in favor of Spirit.
=> Break ties for Spirit vs. Hit Reforges for hybrid casters

ui/mage/arcane/sim.ts, ui/mage/fire/sim.ts, ui/mage/frost/sim.ts, ui/paladin/retribution/sim.ts
- Added forgotten statCaps property for the Mage ReforgeOptimizer
=> [FIX][MAGE] Added stat caps for mage

ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/individual_sim_ui.tsx
- Moved tab to after results because of muscle memory
- Add link on web version to download local sim for faster results
- Change iterations limits for web and local
=> more bulk sim updates

sim/core/spell_outcome.go, sim/rogue/assassination/TestAssassination.results, sim/rogue/assassination/mutilate.go, sim/shaman/enhancement/TestEnhancement.results, sim/shaman/stormstrike.go, sim/warrior/fury/TestFury.results, sim/warrior/fury/raging_blow.go
fix warrior raging blow hit outcome
fix rogue mutilate hit outcome
fix shaman stormstrike hit outcome
update tests
=> add new melee special outcome that only checks block and crit

ui/core/components/suggest_reforges_action.tsx
=> Ignore soft cap breakpoints for stats with specified hard caps

sim/death_knight/frost/TestFrost.results, sim/death_knight/talents_frost.go
=> Fix Brittle Bones damage bonus

ui/core/components/individual_sim_ui/bulk_tab.tsx
- `this` scope is not passed properly, needed an arrow function
=> Fix clear button error

sim/warrior/fury/TestFury.results, sim/warrior/fury/fury.go, sim/warrior/fury/raging_blow.go, sim/warrior/slam.go, sim/warrior/warrior.go, sim/warrior/whirlwind.go
- update warrior oh proc mask
- update dual wield spec to use oh proc mask
- update tests
=> [Warrior] Fix oh proc mask and update dual wield spec mod

sim/death_knight/frost/TestFrost.results, sim/death_knight/frost/frost.go
=> Update Frost Mastery to Multiplicative

ui/core/preset_utils.tsx, ui/death_knight/frost/presets.ts, ui/warrior/fury/presets.ts
- Fixes reverse DK DW/2H check
- Split message into multiple message per type of warning
=> [FIX] Preset warnings trigger

ui/core/components/suggest_reforges_action.tsx
- Mastery rating input now excludes base mastery value since most/all breakpoint tables refer to rating excluding this. This now also matches with the character stats panel.
- Added tooltip explaining displayed rating vs %
=> [UI] Reforge Optimizer base mastery values

sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/ghoul_pet.go, sim/death_knight/unholy/TestUnholy.results
=> Fix DK Ghoul Str Scaling

ui/core/components/stat_weights_action.tsx, ui/core/components/suggest_reforges_action.tsx, ui/core/individual_sim_ui.tsx, ui/scss/core/components/_stat_weights_action.scss
- Allows opening of EP weights menu from the reforge optimizer
- Removed experimental code for tank/threat EP
=> [UI] Make tank EPs non-experimental

ui/core/components/character_stats.tsx
Added a tooltip for haste in the Character panel due to yesterdays haste changes now showing 0 at buffs
=> [UI] Add haste tooltip message

sim/core/cast.go, sim/core/gcd.go, sim/death_knight/blood/TestBlood.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/protection/TestProtectionWarrior.results
Reverting https://github.com/wowsims/cata/pull/723 for now as we discovered several unintended mechanical changes that lowered DPS by more than expected
=> revert #723

sim/paladin/holy_wrath.go, sim/paladin/inquisition.go, sim/paladin/paladin.go, sim/paladin/retribution/TestRetribution.results
* Simplify the spell mod for Inquisition to just use School instead of ClassSpellMask
* Actually set a ClassSpellMask for Holy Wrath to make it proc Divine Purpose and Ancient Power
=> [Ret] Simplify Inquisition mod and fix Holy Wrath for some procs

ui/core/components/suggest_reforges_action.tsx, ui/core/sim_ui.tsx, ui/mage/arcane/sim.ts, ui/mage/fire/sim.ts
Mage community managers get a lot of questions about Fire mage sim and the volatility of the breakpoints (which aren't configured). Talked to them and decided to put it behind experimental for now.
=> [UI][MAGE] Reforge Optimizer behind Experimental

sim/core/database.go, sim/core/stats/stats.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results
Fixed random suffix stats to round down to the nearest integer like they do in-game.
On branch random_suffixes
modified:   sim/core/database.go
modified:   sim/core/stats/stats.go
=> Random Suffix Rounding Fix

sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/ghoul_pet.go, sim/death_knight/unholy/TestUnholy.results
=> Update DK Ghouls base Crit

sim/encounters/bwd/nefarian_ai.go
@NerdEgghead I just added a target fix so it would work on non-tank sims, just like the magmaw ai has; not that it makes sense to sim this as a dps, but as it stands it will break the sim. Feel free to merge if it has no drawbacks.
fixes #665 
fixes #639
=> update nefarian ai casts on non tank sims

sim/warrior/fury/TestFury.results, sim/warrior/fury/talents.go, sim/warrior/warrior.go, sim/warrior/whirlwind.go, ui/core/proto_utils/action_id.ts
- fix flurry consuming stacks on non melee hits
- fix meat cleaver triggering on spell hit instead of cast complete 
- add whirlwind oh spellmask
- fix whirlwind cd reduction to 4 or more targets
- fix whirlwind to show mainhand/offhand damage in the ui
=> [Warrior] Fury fixes

proto/api.proto, sim/core/api.go, sim/core/bulksim.go, sim/wasm/main.go, sim/web/main.go, ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/sim.ts, ui/core/worker_pool.ts, ui/worker/sim_worker.ts, ui/worker/types.ts, ui/worker/worker_http.ts
=> Revert "[Batch Sim] Calculate combinations/iterations from the back-end's real calculations"

ui/warrior/fury/presets.ts, ui/warrior/fury/sim.ts
- Recalculated Fury SMF & TG EPs
- Added Fury hit softcap EPs
=> [WARR][FURY] Add softcaps for TG and SMF

sim/death_knight/blood/TestBlood.results, sim/death_knight/death_strike.go, sim/death_knight/presences.go, ui/death_knight/blood/sim.ts
- Fixes #805 
- Add the Health Bonus from Blood Presence to the Stats Panel
=> Blood DK Fixes

sim/core/consumes.go, sim/core/stats/stats.go, sim/core/unit.go, sim/warrior/arms/TestArms.results, sim/warrior/arms/arms_test.go, sim/warrior/fury/TestFury.results, sim/warrior/fury/fury_test.go
- Helper function to facilitate the implementation of procs that use the highest value between multiple stats.
- Refactored the synapse springs to use the helper function
- Added synapse springs to warrior dps tests
=> Implement highest stat helper function

sim/core/debuffs.go, sim/death_knight/frost/TestFrost.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/bm_talents.go, sim/hunter/cata_items.go, sim/hunter/cobra_shot.go, sim/hunter/hunter.go, sim/hunter/marksmanship/TestMM.results, sim/hunter/pet_abilities.go, sim/hunter/steady_shot.go, sim/hunter/survival/TestSV.results, tools/database/overrides.go
=> [Hunter] Fix Pet stuff, Tier implementations, BW fix

ui/core/launched_sims.ts, ui/index.html
* Mark Retribution as Beta
* Fix Protection link on start page to reflect Alpha state
=> [Paladin] Mark Retribution as Beta and fix Protection on start page

ui/core/components/suggest_reforges_action.tsx, ui/priest/shadow/presets.ts
- Fixed wrong sorting in Shadow breakpoint preset
- On Threshold now always show postCapEP on all breakpoints
=> Fix visual inconsistencies

ui/hunter/beast_mastery/sim.ts, ui/hunter/marksmanship/sim.ts, ui/hunter/shared.ts, ui/hunter/survival/sim.ts, ui/mage/arcane/sim.ts, ui/mage/fire/sim.ts, ui/mage/frost/sim.ts, ui/mage/shared.ts
- Added Piercing Ice talent to modify crit in display stats
- Moved 3x repeated hunter display modification to shared re-used logic
=> [MAGE] Display stat talents

ui/shaman/enhancement/presets.ts, ui/shaman/enhancement/sim.ts
- Added suggest reforge
- Added soft caps
- Recalculated proper EPs
=> [SHAMAN] Enhancement - Suggest reforge and EPs

.github/labels.yml, .github/workflows/pr_labeler.yml
Saw this out in the wild and it looks pretty lit to have extra organization with 0 effort essentially. If we merge, maybe add some more labels such as core, ui, build, deps
Thoughts?
Format is:
```yaml
Label:
- glob/patterns/**/*
```
=> PR Labeler Workflow

ui/mage/arcane/sim.ts, ui/mage/fire/sim.tsx
- Seems much more reliable without any complaints about bad suggestions the past week
=> [MAGE] Remove suggest reforge experimental flag

sim/warrior/arms/TestArms.results, ui/warrior/arms/gear_sets/p1_arms_bis.gear.json, ui/warrior/arms/gear_sets/p1_arms_realistic_bis.gear.json, ui/warrior/arms/presets.ts, ui/warrior/arms/sim.ts
- Updated P1 Arms to P1 Arms - BIS and included the actual RNG heavy BIS (TOT4W random suffixes)
- Added P1 Arms - Realistic BIS (the old P1 preset which is not actual BIS but RNG friendly BIS)
- Changed Alliance default race to Worgen
=> [WARRIOR] Update Arms BIS presets

.github/workflows/deploy.yml
On branch versioning_workflow
modified:   .github/workflows/deploy.yml
=> Automatically merge PR for .deployedprotoversion update

.github/workflows/deploy.yml
#873 errored out on an even earlier step, so try the automatic PR merge with full default permissions
=> Try again with all default permissions

go.mod, go.sum, ui/core/encounter.ts, ui/core/proto_utils/stats.ts
- Added fallback stats in case the stats migration would migrate invalid `Stat[]`
- Added `protobuf` as dependency to fix it not updating locally
=> [UI] Add fallback stats migration option

sim/mage/fire/TestFire.results, ui/mage/fire/gear_sets/p1_fire.gear.json, ui/mage/fire/gear_sets/p1_fire_prebis_gear.json
- Updated P1 BIS meta gem
- Updated P1 Pre-raid and BIS reforges using improved suggest reforge
=> Update proper reforges & p1 bis gem

sim/death_knight/frost/TestFrost.results, sim/warrior/fury/TestFury.results, sim/warrior/fury/bloodthirst.go, sim/warrior/fury/raging_blow.go
Fixed Bloodthirst multiplier and incorrect procmask on Raging Blow for Fury
=> Bt rb fixes

sim/common/cata/damage_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results
Using 4.3 simc value for now until we can test it
=> update firelands capacitor proc chance

ui/core/components/gear_picker/item_list.tsx
=> temporary phase fix for gear not showing

sim/warlock/destruction/TestDestruction.results, ui/warlock/destruction/apls/default.apl.json
- Adds missing 4PC proc (Fel Spark) to Destro APL
=> Add Fel spark to Destruction APL

sim/core/bulksim.go
Created a new signal object to "cancel reporter" in bulk sim code instead of reusing the one for the request. Maybe fixes the random sim cancelled some(one) in Discord reported.
=> Maybe fix bulk sim cancelling itself?

ui/core/components/gear_picker/item_list.tsx
Removed the `Show EP` button and `EP` column from Trinket 1 and 2 item lists
=> [UI] Remove EP button/colunn from Trinkets

ui/core/components/detailed_results/metrics_table/metrics_table.tsx, ui/core/components/raid_sim_action.tsx, ui/scss/core/components/_detailed_results.scss, ui/scss/core/components/detailed_results/_topline_results.scss
Removes old code I forgot to remove when refactoring results
=> [FIX] Remove debugging code

sim/common/cata/damage_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/mind_flay.go, sim/priest/shadow/TestShadow.results, sim/priest/shadow/shadow_test.go, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results
=> Fix Variable Pulse Lightning Capacitor

ui/priest/shadow/sim.ts
- Added Mastery flooring to Shadow reforge
=> [UI][PRIEST] Add reforge Mastery breakpoints

sim/mage/fire/TestFire.results, sim/mage/items.go, sim/mage/talents_fire.go
- Add Piercing Ice to HS base crit percentage
=> [FIX][MAGE] HS T3 piercing ice

sim/hunter/cata_items.go, sim/paladin/items.go, sim/warrior/items.go, ui/core/proto_utils/action_id.ts
Merged the following DPS metrics for T12 2/4P
- Paladin DPS / Tank
- Warrior DPS / Tank
- Hunter
**Hunter**
**Paladin - Ret**
**Paladin Prot**
**Warrior - Arms/Fury**
**Warrior - Prot**
=> [UI] Merge T12 Passive procs

ui/mage/arcane/sim.ts
=> Revert "[FIX] Arcane - Faulty EP post cap code"

sim/mage/arcane/TestArcane.results, ui/mage/arcane/gear_sets/p1_arcane.gear.json, ui/mage/arcane/presets.ts
Makes sure breakpoint softcap will actually execute
=> [FIX] Arcane EP

ui/core/components/encounter_picker.ts, ui/core/components/input.tsx
On branch feature/preset-configurations
modified:   ui/core/components/encounter_picker.ts
modified:   ui/core/components/input.tsx
=> Fix target input labels not changing when swapping presets

sim/paladin/retribution/TestRetribution.results, sim/paladin/retribution/retribution_test.go, ui/paladin/retribution/gear_sets/preraid.gear.json, ui/paladin/retribution/gear_sets/t11_bis.gear.json, ui/paladin/retribution/presets.ts, ui/paladin/retribution/sim.ts
* Update preraid gear preset
* Update reforges on T11 preset
* Update T11 ep weights
* Add T12 gear preset, ep weights and talent/glyph preset
* Make auto and simple rotation types pick T13 rotation if 2pc is equipped
=> [Ret] Update existing presets and add T12

ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/gear_picker/item_list.tsx, ui/core/components/item_notice/item_notice.tsx, ui/core/constants/item_notices.tsx
For: https://github.com/wowsims/cata/pull/989
- Added an item notice component to explicitely add information/warnings for items such as DTR.
- Allows Generic and spec specific content
=> [UI] Add Item Notices

ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/gear_picker/item_list.tsx, ui/core/components/item_notice/item_notice.tsx, ui/core/constants/item_notices.tsx
- Add notice to DTR to inform users that it's not implemented but being worked on.
=> [UI] Add DTR item notice

ui/core/components/item_notice/item_notice.tsx, ui/core/constants/item_notices.tsx, ui/core/individual_sim_ui.tsx, ui/core/proto_utils/database.ts
modified:   ui/core/components/item_notice/item_notice.tsx
modified:   ui/core/constants/item_notices.tsx
modified:   ui/core/individual_sim_ui.tsx
modified:   ui/core/proto_utils/database.ts
=> Item notices for missing / tentative set bonus implementations

sim/common/cata/damage_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, ui/core/constants/item_notices.tsx
- Adjusted proc rate to 50% based off @InDebt research
- Added proc rate warning
=> [FIX] Adjust VPLC proc rate and add warning

sim/core/runic_power.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/dancing_rune_weapon.go, sim/death_knight/death_knight.go, sim/death_knight/diseases.go, sim/death_knight/frost/TestFrost.results, sim/death_knight/icebound_fortitude.go, sim/death_knight/items.go, sim/death_knight/unholy/TestUnholy.results, ui/core/proto_utils/action_id.ts
- Adds T12 2/4PC for DK DPS
- Adds T12 2/4PC for DK Tank
**Tank**
=> [DK] Add Tank/DPS T12 set

ui/core/constants/item_notices.tsx
Adds a notice for the trinkets not yet implemented in #902
I have begun work on implementing them but this should do until that's finished.
=> [UI] Add item notices for NYI trinkets

sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/talents.go, ui/warrior/protection/sim.ts
- Implemented Toughness as DK has it
=> [WARRIOR] Fix core toughness implementation

sim/druid/feral/rotation.go
modified:   sim/druid/feral/rotation.go
=> Block Primal Madness cancellation during Berserk

ui/core/components/raid_sim_action.tsx, ui/core/constants/tooltips.ts, ui/core/proto_utils/sim_result.ts
Fixed topline results label for TMI, increased sig figs for TMI and COD error bars, and added statistical significance display for COD.
On branch guardian
modified:   ui/core/components/raid_sim_action.tsx
modified:   ui/core/constants/tooltips.ts
modified:   ui/core/proto_utils/sim_result.ts
=> Tank metrics display improvements

sim/priest/shadow/TestShadow.results, sim/priest/shadow/shadow.go, ui/core/components/item_notice/item_notice.tsx, ui/core/constants/item_notices.tsx
- Allow Item Notices to ignore certain specs
- Removed VPLC warning for Mage, Warlock & Shadow Priest
- Removed Shadow's Shadow Power Mask as it also applies to VPLC & DMC:V
=> [PRIEST][UI] Adjust VPLC warning & Shadow Power mask

sim/common/cata/damage_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/balance/TestBalance.results, sim/druid/balance/balance_test.go, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/druid/talents.go, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results
- Adjust VPLC Normal damage according to database as tooltip is faulty
- Removed Balance of Power's incorrect class mask
- Removed Moonkin Form's incorrect class mask
- Add Balance Test
=> Fix VPLC N damage range & class masks

ui/core/constants/other.ts, ui/core/launched_sims.ts, ui/index.html
We haven't had any major issues/reports with the Sims so I think it's time to mark them all as Phase 2 - Launched
=> [UI] Make all current Sims Launched

sim/warlock/affliction/TestAffliction.results, sim/warlock/glyphs.go
- The glyph was increasing the cast time instead of decreasing
=> [WARLOCK] Reverse UA glyph cast time logic

sim/death_knight/talents_unholy.go, sim/death_knight/unholy/TestUnholy.results
Fixes #1047 
Confirmed as well by how simc has it implemented
=> [Unholy] Fix Runic Corruption to extend duration if already active

sim/core/cast.go, sim/warlock/demonology/TestDemonology.results
- Fixes an issue where simple cast functions would go on CD if the shared timer failed.
=> [CORE] Fix simple casts going on CD

sim/shaman/lightning_bolt.go
Allows Shaman to cast LB whilst moving
=> Add Glyph of Unleashed Lightning

sim/common/cata/damage_procs.go, sim/shaman/chain_lightning.go, sim/shaman/elemental/TestElemental.results, sim/shaman/elemental/thunderstorm.go, sim/shaman/enhancement/TestEnhancement.results, sim/shaman/fire_totems.go, sim/shaman/firenova.go, sim/shaman/items.go, sim/shaman/lavaburst.go, sim/shaman/lightning_bolt.go, sim/shaman/shocks.go, sim/shaman/talents.go, sim/shaman/unleash_elements.go, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results
Changed 4PT12 logic with Elemental Mastery
Added travel time to VPLC projectile
Added Variance to ele spells
=> [Elemental] Update to 4PT12 based on ptr testing

sim/common/cata/dragonwrath.go, sim/druid/balance/TestBalance.results, sim/mage/fire/TestFire.results, sim/priest/shadow/TestShadow.results, sim/priest/shadow/dragonwrath.go, sim/shaman/elemental/TestElemental.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results
* Make replicatino spell last in current sim step to remove auras properly on damage before replication
* Supres Shadowy Apparition
=> [DTR] Small fixes

sim/warlock/affliction/TestAffliction.results, sim/warlock/affliction/affliction.go, sim/warlock/affliction/affliction_test.go, sim/warlock/demonology/TestDemonology.results, sim/warlock/demonology/demonology_test.go, sim/warlock/demonology/metamorphosis.go, sim/warlock/glyphs.go
See also: https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/1256
=> warlock: remove mastery flooring for meta and affliction

proto/ui.proto, sim/druid/balance/TestBalance.results, sim/druid/eclipse.go, sim/mage/fire/TestFire.results, sim/mage/fire/fire.go, sim/mage/talents_fire.go, sim/priest/shadow/TestShadow.results, sim/priest/shadow/shadow.go, sim/rogue/assassination/TestAssassination.results, sim/rogue/assassination/assassination.go, sim/rogue/subtlety/TestSubtlety.results, sim/rogue/subtlety/subtlety.go, ui/druid/balance/gear_sets/t12.gear.json, ui/druid/balance/sim.ts, ui/mage/fire/gear_sets/p3_fire.gear.json, ui/mage/fire/sim.tsx, ui/priest/shadow/sim.ts, ui/rogue/assassination/gear_sets/p1_assassination.gear.json, ui/rogue/assassination/gear_sets/p3_assassination.gear.json, ui/rogue/assassination/sim.ts, ui/rogue/combat/sim.ts, ui/rogue/subtlety/sim.ts
- Removed backend class Mastery flooring
- Removed frontend class Mastery flooring
=> [UI][CORE] Remove mastery flooring from all non-warlock classes

sim/warrior/arms/TestArms.results, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/rend.go
Rend had the wrong outcome and snapshot wrapper
=> update rend outcome and change to physical snapshot

sim/warrior/arms/TestArms.results, sim/warrior/arms/talents.go, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/rend.go, sim/warrior/talents.go
I left the ApplyRollover function in, since then I discovered that subtlety's rupture has a similar mechanic. It could be updated to use the wrapper instead of doing it manually, if it makes sense.
=> Revert rend changes

sim/core/apl_values_aura_sets.go
With and without this change with this [setup](https://wowsims.github.io/cata/shaman/elemental/#eJztVV1oHFUUnnPu3d27JzG5uWnCeG1xMlZZhkZnZ63dLpjd5CmUIqH0IT4GUn+KDyHxRZ92tZS4VtREqNnUhwYfxIa0DT6IUkjLShV/CBFCVShaLKxaqKQgtD7onZlNCE2FPoiCeGCXe873ne/8zJ1delCAhBI8A2MwCfA2wHsASwCXABoAZYRJhDMIA1wYkrL0u201lhx6buSFQ+MiJVO6AdQul05z+7rjJudn+PXjjFrlmQXuMnPMzIHxjhi44UQBIlld4Pa0k3kTSMmyQY6aRIP8GrNJVgx+sscFi6SsGPxVxw1Vrcx0WGp1nkf0UPy1UOJlQ5lyNmJzIWnWSEzGBcM6rfLsfLOfY0ApObPAwzCXv81y8738IaMuuXCK2xXHTcc6IfcokEVpeeJ0nOu2iITfNcSH+RsA3vdoM7oE1n/UVPlfH61gDeAYrMEu7VFGoHI9Ya4qs9GBgAtu88KGX4JBNoTDYMNHuD3n5wI/yAXZIMhls342F/QGftZ8cn5wAXeKj+soP6ijfeMUd87XMXOujv7KVcz/fhlLN1dw8NYKfop8GVu+ResK1oR5zp0kdJK4qFW5m6IEsd7cBHVQUnNCu6MZyk6QopQ2RzHNNmKKayxYKq1j5JVu9SPqH5BWUX+NtEftpoz3kGDqnkUkAcpwNe6zdOciSuOyWsLSkVTgT1B6EcIuzt1kdBzV …
=> Aura Sets - Removed trinkets that cant proc from NumEquippedStatProcTrinkets

sim/shaman/enhancement/TestEnhancement.results, ui/shaman/enhancement/apls/default.apl.json
Consistently >100 dps above previous APL on all fight lengths between 120-420s, equal on 60s
=> [Enh] Tweak APL to gain a bit of deeps

sim/common/cata/other_effects.go, sim/paladin/glyphs.go, sim/paladin/items.go, sim/paladin/retribution/TestRetribution.results, sim/warrior/arms/TestArms.results, ui/core/proto_utils/action_id.ts, ui/paladin/retribution/apls/apparatus.apl.json
Also fixed aura timeline display for Apparatus and Glyph of Exorcism
=> [Ret] APL Tweaks

sim/death_knight/frost/TestFrost.results, ui/death_knight/frost/apls/masterfrost.apl.json, ui/death_knight/frost/gear_sets/p3.masterfrost.gear.json, ui/death_knight/frost/sim.ts
=> [Frost] Fix haste fakepoint between 1746 and 1747 rating

sim/warrior/items.go
* The same damage absorption aura helper used for Savage Defense, Paladin T13 and some trinkets can be used for this 👍
=> [Prot] Implement Prot Warrior T13 2pc correctly with absorb helper

sim/death_knight/items.go, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/shaman/feral_spirit.go, sim/shaman/items.go, sim/shaman/shaman.go, ui/core/constants/item_notices.tsx
* Implemented Enhancement T13
* Snuck in some more item notices for missing tier set bonus implementations
=> [Enh] Implement Enhancement T13

sim/warlock/demon_soul.go, sim/warlock/demonology/TestDemonology.results
- Changed incorrect CastTime spell mod to modify players cast speed
=> [WARLOCK] DS:FG Change CastTime mod to CastSpeed

sim/core/test_result_compare.go, sim/paladin/ancient_guardian_pet.go, sim/paladin/items.go, sim/paladin/protection/TestProtection.results, sim/paladin/retribution/TestRetribution.results, sim/paladin/talents_protection.go, ui/paladin/retribution/presets.ts
* Seals of the Pure should be additive **and apply to Censure**
* PvP gloves CS bonus should be additive, not multiplicative
* Set a higher tolerance for threat SumSq tests because of some rounding errors causing test failures
=> [Ret] Some spell mod bug fixes

sim/death_knight/unholy/TestUnholy.results, sim/rogue/subtlety/TestSubtlety.results, ui/rogue/assassination/presets.ts, ui/rogue/subtlety/gear_sets/p4_subtlety.gear.json
Title
Something made a one-digit Unholy test change for Bryntroll healing
=> [Rogue] Updates to Asn EP weights and P4 Subtlety gearset

sim/core/apl_value.go, sim/paladin/retribution/TestRetribution.results, ui/core/components/detailed_results/timeline.tsx, ui/core/proto_utils/action_id.ts, ui/paladin/retribution/apls/default.apl.json
Also cherry-picked a fix from #1253 to actually make NumStatBuffCooldowns work
=> [Ret] Rework APL to better align with second Guardian

ui/core/components/suggest_reforges_action.tsx
- Resets the gear to the previous state when the reforger errors
=> [UI] Add previous gear fallback on error

ui/core/components/suggest_reforges_action.tsx
Dynamically increase max iteration count for Reforge LP solver when no feasible solution is found. This greatly increases the likelihood that a solution is ultimately obtained for the hardest gear sets, and also lowers the default iteration count required for most gear sets.
=> Dynamically increase max iteration count for Reforge LP solver

sim/common/cata/stat_bonus_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/balance/TestBalance.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/protection/TestProtection.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
Merging separately from #1253 for a cleaner final unit test comparison in #1253 .
=> Implement Seal of the Seven Signs

sim/hunter/beast_mastery/TestBM.results, sim/hunter/cata_items.go, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results
For cleaner final unit test results comparison in #1253 .
=> Another benign RNG seed label change

sim/core/spell_mod.go, sim/rogue/assassination/TestAssassination.results, sim/rogue/assassination/assassination.go, sim/rogue/assassination/venomous_wounds.go, sim/rogue/combat/TestCombat.results, sim/rogue/items.go, sim/rogue/subtlety/TestSubtlety.results, sim/rogue/subtlety/shadowstep.go, sim/rogue/subtlety/subtlety.go
- Fixes Slayer 4-set accidentally adding 600% Damage
- Clean up Assa Mastery logic
=> Fix mastery logic and slayers gear

sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/mage/items.go, ui/mage/arcane/apls/arcane.apl.json, ui/mage/arcane/gear_sets/p4.gear.json, ui/mage/arcane/presets.ts, ui/mage/arcane/sim.ts
- Fix T13 4PC for Arcane
- Add P4 set
- Add T13 2P APL specific settings
=> Add Arcane P4

sim/core/item_swaps.go, sim/shaman/elemental/TestElemental.results
=> Actually fix the initialized check

sim/common/cata/enchant_effects.go
- Add missing proc handling for Hurricane Enchant
=> Fix Hurricane proc triggers

package-lock.json, package.json, ui/core/components/detailed_results/timeline.tsx, ui/index_template.html
- Should fix the issue where countries that have certain CDNs blocked can still use the Sim.
=> Swap to self-hosted apex-charts

sim/hunter/bm_talents.go
Fixes https://github.com/wowsims/cata/issues/1393
=> fix hunter Killing Streak without pet selected

ui/core/components/detailed_results/timeline.tsx, ui/scss/core/components/detailed_results/_timeline.scss
=> improve the visuals of the DPS chart

sim/core/buffs.go, sim/mage/arcane/TestArcane.results, sim/mage/mage.go, sim/mage/talents_arcane.go
- Fixes Arcane Power and PoM being used together
- Fixes Arcane Power not overriding PI
=> Add shared CD and mana cost exclusive effect

sim/rogue/poisons.go
=> [Rogue] I did something dumb

sim/core/mana.go, sim/shaman/electric_spell.go, sim/shaman/lavaburst.go, sim/shaman/shocks.go, sim/shaman/totems.go
Changes base mana cost pecent to a float to.
Mostly needed for MoP branch but here to verify changes are actually valid.
=> [Feature] Allow floats for BaseManaCostPct
