ui/core/player_classes/death_knight.ts, ui/core/player_classes/druid.ts, ui/core/player_classes/hunter.ts, ui/core/player_classes/index.ts, ui/core/player_classes/mage.ts, ui/core/player_classes/paladin.ts, ui/core/player_classes/priest.ts, ui/core/player_classes/rogue.ts, ui/core/player_classes/shaman.ts, ui/core/player_classes/warlock.ts, ui/core/player_classes/warrior.ts, ui/core/talents/talents_picker.tsx, ui/druid/_feral_tank/index.html
`name` was not a property existing on the spec class.
It's a bit iffy why this was even allowed through the tsc typechecker.
=> Use friendly name for talents

README.md, makefile, sim/web/main.go, ui/worker/local_worker.js, vite.config.js
Introducing a new command `WATCH=1 make devmode`.
This new dev mode essentially uses the Vite Dev server, meaning we get automatic reloads on saving ts files and go files.
Since we only build what is absolutely necessary in this mode, you get sub-second reloads on ts changes, and recompiling the go server also only takes a few seconds. 
This allows for high productivity development.
To get this to work, I had to modify the Vite dev server a bit, mainly to allow serving of assets in the /assets folder instead of /dist. I also had to add another worker js to send requests to the go server through POST requests. This is because we don't want to have to reload the page when we update the Go code in the sim.
**This is currently very experimental and although it works on my machine, it might …
=> Vite Dev Server implementation

sim/core/base_stats_auto_gen.go, sim/death_knight/unholy/unholy.go, tools/base_stats_parser.py
Mastery isn't converted directly to a percentage until Mists. This conversion factor is for Mastery Rating -> Mastery Points in Cataclysm, so the names should match. Figured this might cause some confusion once more people start looking into implementing masteries.
This was part of a change to add the arms warrior mastery but I wanted to get this in now before more code depends on the existing naming.
=> Rename MasteryRatingPerMasteryPercent to MasteryRatingPerMasteryPoint

sim/core/vengeance.go
More prep work for warrior masteries this time for prot in particular, based on what I could find in simc/wiki pages.
As commented I'm unsure about the exact behavior around non-hit attacks as the information I could dig up was conflicting without any patch notes to mark if/when it changed (aside from a note in 5.4 about dodges and parries continuing to work as they used to, but there's not enough to say if that only became a thing in MoP).
This is all easily tunable later once we can collect more data though. For now this should be enough to let people implement their tank specs.
=> Basic vengeance implementation

sim/core/database.go, ui/core/components/gear_picker.tsx, ui/core/player.ts, ui/core/proto_utils/database.ts, ui/core/proto_utils/equipped_item.ts, ui/core/proto_utils/gear.ts, ui/core/proto_utils/names.ts, ui/scss/core/components/_gear_picker.scss
This commit is a proposal on how we can add Reforging to the UI.
**(Some eslint/prettier stuff snuck through in some files, but its according to the config file so should be fine)**
First, I've added a visualisation on reforged items in the character display:
I went with not showing stats at this stage because its not that relevant.
Then I added a new tab on the gear picker for reforging:
Now, I know the design leaves something to be desired here, especially in the gear picker. So I eagerly accept PRs with nicer UI :D
I also fixed some bugs that made reforged stats not calculate properly. The reforged stat now also exports to json etc. like
```    "equipment": {
"items": [
{"id":65206,"enchant":3817,"gems":[41398,52258]},
{"id":67137}, …
```
=> [Reforging] Add basic Reforging UI

sim/core/constants.go, sim/core/spell_outcome.go, sim/core/unit.go
Pulls the avoidance calculations previously in spell_outcome out into methods on core.Unit so sims can access them without duplicating the math. 
This doesn't include effects like increased miss chance or target dodge chance reduction on the attacker as combat table coverage is generally calculated using only effects on the defender and assuming an attacker level of player_level + 3. See https://wowpedia.fandom.com/wiki/CTC
=> Add avoidance calculation methods

tools/database/wowhead_tooltips.go
* Spell values with thousands seperator should now be properly parsed
Nothing really more to it. Spell values like `3,145` could not be parsed before
=> [DB] Fixup spellpower parsing for values > 1k

proto/apl.proto, sim/core/apl_value.go, sim/core/apl_values_core.go, sim/core/dot.go, ui/core/components/individual_sim_ui/apl_values.ts
* Added a new APL to query the DoT frequency. This should allow for easy checks (Remaining Time < DoT Frequency) to allow re-applying DoTs without clipping them.
* All player DoTs should be affected by haste and thus automatically be affected by the patch
* The tick that gets carried over to the new dot also profits from the new snapshots - see sources in the commit
* Further reasearch if all DoTs in general are affected by these changes or if there are exeptions and how HoTs behave
=> [Core] Implement DoT haste scaling for Cataclysm

ui/core/player_spec.ts, ui/core/player_specs/death_knight.ts, ui/core/player_specs/druid.ts, ui/core/player_specs/hunter.ts, ui/core/player_specs/mage.ts, ui/core/player_specs/paladin.ts, ui/core/player_specs/priest.ts, ui/core/player_specs/rogue.ts, ui/core/player_specs/shaman.ts, ui/core/player_specs/warlock.ts, ui/core/player_specs/warrior.ts, ui/core/talents/talents_picker.tsx
Talent trees were not properly updating their states on page refreshes and preset updates
=> Fix Talent Tree locks

ui/core/components/inputs/buffs_debuffs.ts, ui/druid/feral/presets.ts, ui/druid/feral/sim.ts, ui/shaman/enhancement/sim.ts
modified:   ui/core/components/inputs/buffs_debuffs.ts
modified:   ui/druid/feral/presets.ts
modified:   ui/druid/feral/sim.ts
modified:   ui/shaman/enhancement/sim.ts
=> Added default consumes/buffs/debuffs for Feral sim

sim/core/character.go, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/hunter/survival/TestSV.results, sim/priest/shadow/TestShadow.results
Was the most efficient option to correctly reflect haste auras for melee and spell in the UI as they're also included in the blizzard character frame. Should only inlcude static haste mods that are present during build phase. So primarily talents and buffs.
=> Update stat measurement to include const haste auras

sim/common/cata/damage_procs.go, sim/common/cata/enchant_effects.go, sim/common/cata/other_effects.go, sim/common/cata/stat_bonus_procs.go, sim/common/cata/stat_bonus_stacking.go, sim/common/shared/shared_utils.go
Uses spellIDs that will match player's combat logs where possible to make it easier to compare logs to sims.
=> Use friendlier ActionIDs for effects from items and enchants

sim/druid/feral/TestFeral.results, sim/druid/feral/apl_values.go, sim/druid/feral/feral.go, sim/druid/feral/rotation.go, sim/druid/ferocious_bite.go, sim/druid/rip.go
- Changed end-of-fight threshold for Rake usage to only 1 tick required before it is worth casting over Shred.
- Fixed bug in Mangle clipping calculation.
- Prioritize Rake uptime over only spending Clearcasting on Shred.
- Added end-of-fight check to Roar pooling logic.
- Delay Roar clips when an additional CP would cover us to end of fight.
- Added CP check to Roar pooling logic.
- Replaced hardcoded 10s rule for end-of-fight Bite usage with a more accurate DPE-based calculation.
- Removed 67 Energy threshold for Bite usage that was left over from WotLK.
- Prioritize Rip over Savage Roar at 5 CP when both are down.
=> Feral Rotation Optimizations

sim/common/cata/other_effects.go, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results
Fury of Angerforge had his on-use cooldown set to 2 minutes.
Heart of Ignacious was using Fury of Angerforge itemID as his actionID showing the wrong icon on the ui timeline
=> Update other effects trinkets

sim/core/rage.go
Removed the double rage on crit as it was never implemented and not how original or classic beta works
Fixes bug #191
=> [Warrior] Removed 2x Rage on crit

ui/core/components/character_stats.tsx, ui/core/individual_sim_ui.ts, ui/warrior/arms/sim.ts, ui/warrior/fury/sim.ts, ui/warrior/protection/sim.ts
I was playing around with the new Cata sim and noticed the warrrior sim was not showing Mastery.
- Added missing mastery in character display stats in the Sim UI for Warrior
- Fixed minor typo
=> Fix typo & add Mastery to Warrior display stats

sim/core/consumes.go, ui/core/components/character_stats.tsx, ui/core/components/inputs/consumables.ts, ui/death_knight/blood/sim.ts, ui/death_knight/frost/sim.ts, ui/death_knight/unholy/sim.ts, ui/druid/balance/sim.ts, ui/druid/restoration/sim.ts, ui/hunter/beast_mastery/sim.ts, ui/hunter/marksmanship/sim.ts, ui/hunter/survival/sim.ts, ui/mage/arcane/sim.ts, ui/mage/fire/sim.ts, ui/mage/frost/sim.ts, ui/paladin/holy/sim.ts, ui/paladin/protection/sim.ts, ui/paladin/retribution/sim.ts, ui/priest/discipline/sim.ts, ui/priest/holy/sim.ts, ui/shaman/enhancement/sim.ts, ui/shaman/restoration/sim.ts, ui/warlock/affliction/sim.ts, ui/warlock/demonology/sim.ts, ui/warlock/destruction/sim.ts, ui/warrior/arms/sim.ts, ui/warrior/fury/sim.ts, ui/warrior/protection/sim.ts
- Removed deprecated ArP stat from sim profile (EP & Display)
- Added Mastery to ep/display stats for all profiles
- Updated WOTLK food and elixir with deprecated ArP stat to new stats
=> Remove visual ArP, add missing visual Mastery and food buffs

sim/common/cata/damage_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/enhancement/TestEnhancement.results
agility Darkmoon Card: Hurricane procMask is not set to the correct value making it not proc
Updated according to the implementation of the strength version of the trinket
=> update hurricane procMask

sim/warrior/arms/deadly_calm.go, sim/warrior/arms/mortal_strike.go, sim/warrior/arms/sweeping_strikes.go, sim/warrior/berserker_rage.go, sim/warrior/colossus_smash.go, sim/warrior/fury/raging_blow.go, sim/warrior/inner_rage.go, sim/warrior/recklessness.go, sim/warrior/slam.go, sim/warrior/warrior.go
Recklessness and Deadly Calm cannot be used together, also updated Inner Rage to use the same logic
Slam is affected by haste but the GCD is still 1.5. Would like some feedback on this part if possible.
Multiple spells were missing the IgnoreHaste flag, added the ones I could find.
=> [Warrior] Fixes

ui/core/components/encounter_picker.ts, ui/core/components/list_picker.tsx
Fixes #213 
- Added `minimumItems` prop to the ListPicker enforce a minimum amount of items in the ListPicker to prevent having 0 items if it's not supported
- Hides delete button on `n`entries if `minimumItems` is set
- Targets always expects to at least have 1 entry, which also makes sense. Since there's no reason to have 0 targets (that I can think of), since a user still has to edit it anyways, even when adding a new entry I believed that just making sure you can never has no targets would be an appropriate solution.
=> Fixes #213 - Add minimum item count and fix targets

ui/core/components/gear_picker.tsx, ui/scss/core/components/_gear_picker.scss
Changing gems is quite cumbersome because you need to open the item modal and then manually swap to the Gem. I've added support to also jump to the different gem slot tabs through the small overview gem icon on each gear slot.
Also optimized the check for which list to rerender by looking for the actual available lists and comparing it to what was opened.
https://github.com/wowsims/cata/assets/1216787/5844bb53-668e-4e04-a44f-eda5af261764
=> [UI] Allow gem tab opening from item overview

sim/warrior/arms/glyphs.go, sim/warrior/arms/talents.go, sim/warrior/colossus_smash.go, sim/warrior/fury/glyphs.go, sim/warrior/fury/talents.go, sim/warrior/items.go, sim/warrior/protection/glyphs.go, sim/warrior/protection/talents.go, sim/warrior/talents.go
Updated based on **Apply Aura: Modifies Damage/Healing Done** for additive and **Apply Aura: Mod Damage Done %** for multiplicative
https://www.wowhead.com/cata/spell=58368/glyph-of-mortal-strike
https://www.wowhead.com/cata/spell=12330/improved-slam
https://www.wowhead.com/cata/spell=58367/glyph-of-bloodthirst
https://www.wowhead.com/cata/spell=85738/meat-cleaver
https://www.wowhead.com/cata/spell=90293/item-warrior-t11-dps-2p-bonus
https://www.wowhead.com/cata/spell=90296/item-warrior-t11-protection-2p-bonus
https://www.wowhead.com/cata/spell=58375/glyph-of-shield-slam
https://www.wowhead.com/cata/spell=12799/improved-revenge
https://www.wowhead.com/cata/spell=80980/thunderstruck
https://www.wowhead.com/cata/spell=84572/war-academy
=> Update warrior multipliers and colossus smash

sim/mage/mana_gems.go
Values were in the 3k range beforehand, updated to cata values of 11801 - 12405
=> fixed mana gem values

ui/core/components/gear_picker/quick_gem_popover.tsx
- Quick Swap dropdown now correctly filters gems that are not allowed in the selected socket.
=> [UI] Fix quick swap eligible gems

sim/mage/arcane_blast.go, sim/mage/arcane_explosion.go, sim/mage/talents_arcane.go
- Made Arcane Blast mana scaling Pct
- Removed mana scaling from Arcane Explosion from Arcane Blast debuff
- Fixed Arcane Blast & Arcane Explosion mana costs
- Fixed Arcane Potency being consumed by non-damaging spells
=> Arcane Mage updates

sim/core/apl.go, sim/core/apl_actions_casting.go, sim/core/apl_actions_sequences.go, sim/core/spell.go, sim/core/spell_queueing.go
On branch spell_queueing
modified:   sim/core/apl.go
modified:   sim/core/apl_actions_casting.go
modified:   sim/core/apl_actions_sequences.go
modified:   sim/core/spell.go
modified:   sim/core/spell_queueing.go
=> Fixed spell queueing code to work properly with MCDs within sequences.

ui/core/components/importers.ts
Support for the Cata WowSimsExporter plugin:
- PR for fix here: https://github.com/wowsims/exporter/pull/5
- Added itemID support since that was added and more convenient
=> [Importer] Add prime glyph support for WSE addon

ui/core/components/other_inputs.ts, ui/core/sim.ts
Partially fixes #247 
- Pre-patch is phase 0, thus the `> 0` check had to be removed
- Other filters don't work since `sources` is populated by AtlasLootClassic and there's no Cataclysm dataset yet.
=> [UI] Add fix for phase change filter when 0

sim/druid/feral/TestFeral.results, sim/druid/rake.go
Fixed a bug where Rake flat damage was not scaled down by number of ticks.
modified:   sim/druid/rake.go
=> Rake base damage bugfix

proto/shaman.proto, sim/shaman/elemental/TestElemental.results, sim/shaman/talents.go, sim/shaman/totems.go, ui/shaman/elemental/presets.ts, ui/shaman/enhancement/presets.ts, ui/shaman/inputs.ts
Fixed a crash occruing when loading the new totem call thing with an old incompatible settings
Fixed no travel time spells consuming their own procced Clearcasting
Fixes #308, #298
=> [Shaman] Crash fix and clearcasting bug fix

sim/mage/arcane/arcane_barrage.go, sim/mage/arcane_blast.go, sim/mage/arcane_explosion.go, sim/mage/arcane_missiles.go, sim/mage/blast_wave.go, sim/mage/blizzard.go, sim/mage/combustion.go, sim/mage/deep_freeze.go, sim/mage/dragons_breath.go, sim/mage/fire/pyroblast.go, sim/mage/fire_blast.go, sim/mage/fireball.go, sim/mage/flamestrike.go, sim/mage/freeze.go, sim/mage/frostbolt.go, sim/mage/frostfire_bolt.go, sim/mage/ice_lance.go, sim/mage/living_bomb.go, sim/mage/mage.go, sim/mage/scorch.go
Changed mage spells to use new crit multiplier data (primary modifier = 1.33).
Pets still use default (confirmed in logs).
Added ability for Living Bomb and Flamestrike to crit.
=> [Mage] Crit multiplier change & DoT crits

sim/hunter/beast_mastery/TestBM.results, sim/hunter/beast_mastery/beast_mastery.go
It was using the old value to update the dmg mult in the mastery change callback.
=> Fix BM mastery update on mastery change

sim/core/sim.go, sim/death_knight/blood/TestBlood.results, sim/druid/feral/TestFeral.results, sim/shaman/elemental/TestElemental.results
Changes labeled rands to use the current rand seed instead of the base seed on initialization.
"Lazy initialization" of rarely used labels with the base seed in later iterations causes test differences if going multi-threaded. This fixes that.
=> Fix used rseed on label rand init

sim/shaman/enhancement/TestEnhancement.results, sim/shaman/stormstrike.go, ui/core/proto_utils/action_id.ts
Makes the main Stormstrike spell trigger spells for MH and OH to deal damage, like it does in the game. The previous implementation caused side effects from changing procmasks.
Resolves https://github.com/wowsims/cata/issues/327
=> Make Stormstrike trigger spells

ui/core/components/base_modal.tsx, ui/core/components/gear_picker/gear_picker.tsx, ui/scss/core/components/_gear_picker.scss, ui/scss/core/sim_ui/_main.scss, ui/scss/shared/_global.scss
- Fixed issues with event handlers not being properly disposed of. We have to locally assign the functions then add callbacks to remove them instead of the previous approach.
- This also fixed an issue where re-opening the gear picker caused the up and down arrow functions to run multiple times, leading to "skipping" slots
- Fixed an issue where switching between slots with the up and down arrows caused newly equipped gear to be equipped in the original slot that was opened
- This required changing how the tab switching was handled by going through the actual item picker so that `gearData` is built correctly
- Fixed some mobile style issues (see screenshot)
- Item icons were smaller than the bordered frame
- There were some spacing and alignment issues on the thinnest screens
- Adjusted …
=> Several gear picker issues and styles

sim/core/api.go, sim/core/api_raidsim_concurrent.go, sim/core/api_raidsim_wasm.go, sim/core/bulksim.go, sim/core/bulksim_test.go, sim/core/presim.go, sim/core/sim.go, sim/core/statweight.go, sim/lib/library.go
Adds an optional stop signal channel to the sim. 
If quit channel exists it is checked before every iteration. If a message was received a RaidSimResult containing an error message is returned. If a progress channel exists a ProgressMetrics message is also sent.
Concurrent sim code sends quit signal to all threads in case of an error.
=> Add quit signal to stop threads on error

Dockerfile, README.md, makefile
- Merged some RUN rules for efficiency
- Add Air to Dockerfile dependencies
- Added additional `watch` mode ports
- Added `--host` flag in `devmode` command to allow Docker to expose the host. Shouldn't impact non-Docker users (just local network)
- Updated README with `CATA_WATCH_CMD`
- Updated all outdated Node version references to use the same one everywhere
- Updated outdated NVM version
=> Add support for Docker watch/devmode

proto/common.proto, sim/core/consumes.go, ui/core/components/inputs/consumables.ts, ui/mage/frost/presets.ts
Blizzard made a change to Flame Cap in patch 3.4.1 that causes it to share a cooldown with other potions (https://www.wowhead.com/blue-tracker/topic/us/wrath-classic-patch-notes-version-3-4-1-1490168).
This PR will move Flame Cap from a Conjured item category to a Potion so that it properly reflects this nerf.
Closes #355.
=> Flame Cap Nerf

ui/core/components/gear_picker/gear_picker.tsx, ui/core/proto_utils/action_id.ts
- Adds reforge parameter to show the reforge stats on mouseover
=> Added fix to show reforge on wowhead tooltips in gearpicker

proto/api.proto, proto/ui.proto, ui/core/components/filters_menu.tsx, ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/input.tsx, ui/core/components/number_picker.ts, ui/core/constants/other.ts, ui/core/player.ts, ui/core/sim.ts, ui/raid/raid_sim_ui.tsx, ui/scss/core/components/_filters_menu.scss, ui/scss/core/components/_gear_picker.scss, ui/scss/shared/_global.scss, ui/scss/shared/_modal.scss
- Updated reforge text to include values (Screenshot 1)
- Added ilvl to the gear picker modal and made the modal larger to accommodate space a bit better (Screenshot 2)
- Added sorting by both ILvl and EP in the modal (Screenshot 2)
- Added min and max ilvl filters (Screenshot 3)
- By default disabled all armor types except the spec's primary armor type for Armor Specializationbonus
=> Several improvements to item picker

sim/druid/faerie_fire.go, sim/druid/feral/TestFeral.results, sim/druid/feral/apl_values.go, sim/druid/feral/rotation.go, sim/druid/feral/rotation_aoe.go, sim/druid/swipe.go, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, ui/core/launched_sims.ts, ui/druid/feral/apls/aoe.apl.json, ui/druid/feral/inputs.ts, ui/druid/feral/presets.ts, ui/druid/feral/sim.ts, ui/index.html
- Fixed unmerged test changes from earlier Bison PR
- Fixed bug with Faerie Fire usage in AoE rotation
- Fixed bug in TF Energy threshold calculation for AoE rotation
- Implemented AoE bear-weaving
- Added bear-weaving to default AoE APL and to UI rotation presets
- Removed Suggest Gems button from UI until the feature is developed for Cata
- Set sim to Beta launch status
=> Move Feral DPS sim to Beta

ui/core/components/gear_picker/gear_picker.tsx, ui/core/proto_utils/equipped_item.ts
Currently randomSuffix stats are only applied in the reforge tab which results in some broken UI references.
This PR moves the stats modification to the EquipItem where it belongs.
=> [UI] Add stats modifier to EquipItem

sim/core/rage.go, sim/druid/guardian/TestGuardian.results, sim/warrior/protection/TestProtectionWarrior.results
modified:   sim/core/rage.go
modified:   sim/druid/guardian/TestGuardian.results
modified:   sim/warrior/protection/TestProtectionWarrior.results
=> Implemented Cata formula for Rage gains from incoming damage

ui/core/components/encounter_picker.ts, ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/individual_sim_ui/reforge_summary.tsx, ui/core/player.ts, ui/core/proto_utils/equipped_item.ts
This fixes the modification of the `UIItem` core stats resulting in double random affix / reforge values.
=> Fix database modification of item stats object

ui/core/proto_utils/utils.ts
Fixes off-hand enchants not showing due to shield check also excluding offhand. Removed offhand logic in shield statement, and only check for shield in the offhand statement.
=> [UI] Fix offhand/shield enchant logic

sim/core/consumes.go, sim/mage/arcane/TestArcane.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/destruction/TestDestruction.results
Not sure of the interaction with on-use defensive trinket. Are they still on a different shared cd than the offensives one ?
=> Added shared cd between on-use trinket and synapse

ui/core/wowhead.ts
The wowhead dataset is not an actual URL, thus the data must be decoded before adding to the dataset.
- Fixes `pcs` param for set piece bonuses not working
=> [UI][FIX] Decode URI wowhead data

sim/hunter/survival/TestSV.results, ui/hunter/survival/apls/aoe.apl.json
The previous AOE APL had many problems, the largest of which was being in Aspect of the Fox, leading to essentially infinite focus, presumably due to the targets attacking the player.
The new APL is fixes that and makes some improvements:
- The result with no condition for Explosive Trap seems to always be better.
- Serpent Sting can be ignored since it will be applied passively via Multi Shot, which is a high priority cast.
- Mutli Shot seems to be worth spamming on aoe regardless of target count.
- The Kill Shot wait seems to not matter.
- Explosive Shot should only be used with Lock and Load. The same condition as the single target APL is used, since it's equivalent in dps to only using Explosive Shot when the debuff is not present on the target.
One notable thing still missing is Trap …
=> hunter: fix survival aoe apl

proto/druid.proto, sim/core/buffs.go, sim/druid/balance/balance.go, sim/druid/druid.go, sim/druid/eclipse.go, sim/druid/innervate.go, ui/druid/balance/inputs.ts, ui/druid/balance/sim.ts
Ability to start in solar eclipse
Ability to specify a mastery amount for the initial solar eclipse
Enable self innervate (some stuff about innervate target didn't seem to be working so it's just innervate self for now, not like there's much of a reason to innervate someone else anymore...)
=> [Balance] Enable mastery snapshotting + Innervate

sim/core/debuffs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/arms/blood_frenzy.go, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
fix blood frenzy being overwritten by other bleed effects and losing the phys vuln debuff part
=> fix blood frenzy being overwritten by other bleed effects 

ui/core/components/exporters.tsx, ui/core/individual_sim_ui.tsx
Updated export link so that it now correctly goes to https://sixtyupgrades.com/cata/.. instead of the wotlk site.
from issue: https://github.com/wowsims/cata/issues/557
=> fix: Update sixtyupgrades URLs to use Cata URL instead of Wotlk URL

ui/core/components/character_stats.tsx, ui/core/components/number_picker.ts
Due to a tooltip not existing in the dom until opening we should create the input elements in the `onShow` itself. That way when it hides it can unmount and cleanup the element again.
=> [FIX] Bonus stat number picker

sim/common/cata/stat_bonus_procs.go, sim/shaman/elemental/TestElemental.results
This also affected shaman tests because the shaman apl being used is keeping track of the [battle magic](https://www.wowhead.com/cata/spell=91047/battle-magic) aura, which wasn't the one being used in the [alliance version](https://www.wowhead.com/cata/spell=91048/item-proc-spell-power)
=> fix stump of time (alliance) to use the correct aura id

sim/paladin/retribution/retribution.go, ui/paladin/retribution/apls/default.apl.json
Judgements of the Bold mana return was giving 25% base mana per tick instead of 25% spread over 10 ticks. Also didn't get more ticks with haste.
=> [Ret] Fix Judgements of the Bold and polish APL

ui/core/components/suggest_reforges_action.tsx
Added 1% optimality leeway and increased timeout period to 15 seconds in order to fix certain gear sets that the ILP solver was erroring out on.
=> Auto-Reforge fix for gear sets that were not converging

package.json
Volta can only recognize specific versions and `engine` should at least be 20 if that's what every nvm user gets :)
=> Get engine and volta props aligned with .nvmrc

sim/warrior/fury/TestFury.results, sim/warrior/fury/fury.go, sim/warrior/fury/raging_blow.go, sim/warrior/slam.go, sim/warrior/talents.go, sim/warrior/warrior.go, sim/warrior/whirlwind.go, ui/core/proto_utils/action_id.ts, ui/warrior/fury/apls/fury.apl.json
- Add dual wield specialization to offhand abilities like whirlwind, slam with single minded fury talent and raging blow
- Fix slam off-hand's damage to use OHNormalizedWeaponDamage instead of MHNormalizedWeaponDamage
- Update Raging blow and slam with tags to properly show main-hand/off-hand damage breakdowns in the ui
=> [Warrior] fury fixes

proto/ui.proto, ui/core/components/suggest_reforges_action.tsx, ui/core/individual_sim_ui.tsx, ui/core/player.ts, ui/warlock/demonology/sim.ts
- Move soft cap breakpoints to the Sim UI settings for potential CLI usage
- Make soft cap breakpoints part of Sim UI spec defaults
- Add tooltip that will show if a specific spec has implemented certain stat breakpoints
=> Move breakpoints to ui settings and add tooltip

proto/ui.proto, ui/core/components/suggest_reforges_action.tsx, ui/core/player.ts, ui/core/proto_utils/stats.ts, ui/core/sim.ts, ui/scss/core/components/_suggest_reforges_action.scss
- Added option to toggle soft cap breakpoints (enabled by default) and only shows for classes that have this available/configured
- Changed to double inputs to allow for simultaneous rating and percentage editing
- Mastery will now always be either Rating or % (not points)
=> [UI] Reforge Optimiser stat input changes

ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/scss/core/components/individual_sim_ui/_bulk_tab.scss, ui/scss/core/components/individual_sim_ui/bulk/_bulk_item_search.scss
- Fixes mobile view overflows
- Fixes on screens smaller than ~1500px where the search results container would overflow
- Current: https://i.imgur.com/BEJF3U3.png
- Fixed: https://i.imgur.com/zyklmzV.png
- Made results and item list columns scale based on breakpoints
- Mobile: 1
- Tablet: 2
- Desktop: 3
- Now also follow the width of the parent
- Iterations warning box in sidebar no longer overflows the sidebar
- Boolean inputs columns now are responsive and no longer overflow the sidebar
- Re-ordered some of the deeply nested specific selectors
=> [UI] Bulk responsive fixes

sim/shaman/enhancement/enhancement.go, sim/shaman/weapon_imbues.go
Also added a test to not have it stack with itself when imbued on both weapon
Not sure why enh tests are not failing
=> [Shaman] Fix flametongue imbue being affected by reforges

ui/core/proto_utils/stats.ts
Wrongfully changed `*` and `/` when doing the reforge optimizer stuff. For pseudoStats it needs to be reversed.
=> [UI] Flip dodge/parry visual values

sim/core/bulksim.go, ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/sim.ts
- Added missing `randomSuffixes` and `reforgeStats` to database
- https://github.com/wowsims/cata/issues/711
- https://github.com/wowsims/cata/issues/728
- https://github.com/wowsims/cata/issues/728
- Fix sim breaking when duplicate equipped items were detected (non-unique)
- https://github.com/wowsims/cata/issues/730
- Reset pending state on error
=> [FIX] Bulk sim issues

proto/warrior.proto, sim/warrior/fury/fury_test.go, sim/warrior/protection/protection_test.go, ui/raid/raid_stats.tsx, ui/warrior/arms/presets.ts, ui/warrior/arms/sim.ts, ui/warrior/fury/presets.ts, ui/warrior/fury/sim.ts, ui/warrior/inputs.ts, ui/warrior/protection/presets.ts, ui/warrior/protection/sim.ts
With the addition of APL rotations, there is no need for the old ui options. They were not being used already, it just cleans up the ui.
=> [Warrior] remove unused ui elements

ui/core/components/input.tsx, ui/core/components/suggest_reforges_action.tsx
Disabled inputs when user has soft breakpoints enabled and will set the computed (hard cap) stat to 0 so we don't get hardcap + breakpoint conflicts. This to prevent user error/questions on what is happening.
=> [UI] Disable Reforge Optimizer stat inputs

ui/core/talents/trees/priest.json
Fixes https://github.com/wowsims/cata/issues/756
The talent order for rank 2 and 3 of Mental Agility was flipped:
Old: 
```
"spellIds": [14520, 14781, 14780]
```
Fixed:
```
"spellIds": [14520, 14780, 14781]
````
=> [FIX][PRIEST] Mental agility talent order

ui/core/components/encounter_picker.ts, ui/core/components/gear_picker/filters_menu.tsx, ui/scss/core/components/gear_picker/_filters_menu.scss
Fixes: https://github.com/wowsims/cata/issues/608
Some `getSpec` lookups werent migrated properly to `getPlayerSpec`, resulting in some Spec inputs missing for;
- Offhand options
- Tank-only options
- Healer-only options
=> [FIX] getSpec lookups

ui/core/components/sim_header.tsx, ui/core/individual_sim_ui.tsx, ui/scss/core/sim_ui/_header.scss
We've not made the current import/export Wowhead tool compatible with their new gearplanner, so it's best to disable it for now so we don't get user reports about broken functionalities.
=> [UI] Disabled Wowhead import/export

sim/mage/fire/TestFire.results, sim/mage/fire/fire.go, sim/mage/fire/pyroblast.go, sim/mage/talents_fire.go
Fixed the problem mentioned in the issue #686, when hardcasting any spell before the pyro landed would not trigger the dot.
Also changed the mastery calculation to floor the final instead of the current lineal calculation
=> [Mage] Removed nonempty flag from the pyroblast related dot and mastery fix

ui/scss/shared/_global.scss
Fixes https://github.com/wowsims/cata/issues/439
Adjusted the font sizes to not make the Sim tool scale proportionally with larger displays, but rather scale it a bit more to stay legible whilst enjoying more screen space.
**Current**
**Adjusted**
=> Reduce font sizes on larger displays to improve scaling

sim/core/bulksim.go, sim/core/bulksim_test.go, sim/core/database.go, ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/individual_sim_ui/bulk/bulk_item_picker.tsx, ui/core/components/individual_sim_ui/bulk/bulk_item_picker_group.tsx, ui/core/components/individual_sim_ui/bulk/bulk_item_search.tsx, ui/core/components/individual_sim_ui/bulk/bulk_sim_results_renderer.tsx, ui/core/components/individual_sim_ui/bulk/utils.ts, ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/proto_utils/utils.ts, ui/core/sim.ts, ui/scss/core/components/individual_sim_ui/bulk/_bulk_item_search.scss
Resolves https://github.com/wowsims/cata/issues/709
- For dual wield classes, group weapons into a single bulk slot
- Fix bugs with 2h weapon combinations allowing offhands
- Allow fury warriors to batch sim 2hs in either hand
- Fill in shared slots (ring, trinket, weapon) in results for easier understanding
- I hate combination calculations
=> lots of bug fixes for the batch sim

ui/core/components/importers.tsx
Added https://github.com/wowsims/cata/issues/785 to improve random suffix handling by allowing to migrate them to the proper versions if they are applicable to an item.
When importing from 60U the wrong random suffix will be given. I remove the suffix + reforge to prevent errors. When this happens we inform the user:
=> Remove random suffix and reforge from 60U

proto/api.proto, sim/core/api.go, sim/core/bulksim.go, sim/wasm/main.go, sim/web/main.go, ui/core/components/individual_sim_ui/bulk_tab.tsx, ui/core/sim.ts, ui/core/worker_pool.ts, ui/worker/sim_worker.ts, ui/worker/types.ts, ui/worker/worker_http.ts
Creates a new RPC `BulkSimCombos` that runs the Batch sim's valid combination generation and returns the number of combos and iterations that a real bulk sim would run. I extracted the logic for the combination/iteration calculation into a shared function to be able to do it without running a full bulk sim. When users make changes that would affect the numbers of combinations/iterations, the UI makes a request to the back-end to get updated numbers
=> [Batch Sim] Calculate combinations/iterations from the back-end's real calculations

sim/warrior/arms/TestArms.results, sim/warrior/arms/arms.go
- update arms mastery to use normalized weapon damage and 100ms icd
https://www.wowhead.com/cata/spell=76858/opportunity-strike
https://www.wowhead.com/cata/spell=76838/strikes-of-opportunity
log with 2 mastery proc within 126 ms
=> [Warrior] arms mastery fix

ui/druid/guardian/presets.ts, ui/druid/guardian/sim.ts
Added Balanced EP preset to complement existing default Survival preset, and added soft caps configuration with efficient breakpoints to target for offensively skewed setups.
On branch guardian
modified:   ui/druid/guardian/presets.ts
modified:   ui/druid/guardian/sim.ts
=> Guardian EP Update

sim/hunter/marksmanship/TestMM.results, sim/hunter/mm_talents.go
Should be calculated on 9 ticks due to rollover. It's not exactly as it happens in game, but the easier approx so far:
From Whist on the Hunter Discord:
the second piercing shot does 5808 damage, so the first tick does 5808/8=726, then the remaining 8 ticks do (5808-726) / 8 = 635
=> [MM] Fix Piercing Shots damage

ui/core/components/suggest_reforges_action.tsx, ui/core/proto_utils/names.ts, ui/core/proto_utils/stats.ts, ui/mage/fire/sim.ts, ui/scss/core/components/_suggest_reforges_action.scss
Added a table to display the different breakpoints that are configured for a spec that has them. Highly requested by users that like to see how these are configured.
=> Add breakpoint display

ui/core/components/suggest_reforges_action.tsx, ui/core/proto_utils/gear.ts
Added support for blacklisting item slots in auto-Reforge configuration so that they are not changed by the optimizer.
modified:   ui/core/proto_utils/gear.ts
=> Frozen slots support for auto-Reforge

sim/core/buffs.go
The code was referencing a `Ascension` (probably meant to be Aspiration) talent, which I cannot find anywhere.
Power Infusion CD in cata is 2 minutes and I'm not aware of any talent/glyph that reduces this.
=> [FIX] Remove CDR from Power Infusion

sim/paladin/ancient_guardian_pet.go, sim/paladin/retribution/TestRetribution.results
* Hit from owner should not include Draenei Heroic Presence.
* Expertise conversion was way off.
* Crit should not be inherited and seems to be about 2% after suppression.
=> [Ret] Fix Guardian of Ancient Kings hit, exp and crit stats

sim/common/cata/damage_procs.go, sim/common/cata/other_effects.go, sim/common/cata/stat_bonus_cds.go, sim/common/cata/stat_bonus_procs.go, sim/common/cata/stat_bonus_stacking.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
There seems to be heroic versions of the avengers of hyjal items in the database, but those were not available back in the day, just like the heroic trash loot from tier 11 raids.
Do we even bother implementing the tank's brewmaiden on use? [bubblier](https://www.wowhead.com/cata/item=71334/bubblier-brightbrew-charm) and [bitterer](https://www.wowhead.com/cata/item=71333/bitterer-balebrew-charm)
The legendary staff will require more thought than any of the other items to implement. There needs to be a discussion if we even bother implementing it following simc and old data for now, or we wait for more information.
=> Implement t12 procs

sim/warlock/affliction/TestAffliction.results, sim/warlock/affliction/affliction.go, ui/core/constants/mechanics.ts
The tooltip incorrectly states that a point of mastery gives 1.63% increased periodic shadow damage, but both dbc values and ingame tests show that value to be 1.625 instead.
Tests illustrating the differences ingame:
990 mastery: https://classic.warcraftlogs.com/reports/dMA2t6wLjD7TcCpN#fight=4&type=damage-done&view=events&ability=-172
1000 mastery: https://classic.warcraftlogs.com/reports/dMA2t6wLjD7TcCpN#fight=5&type=damage-done&view=events&ability=-172
=> warlock: fix mastery coef for affli 1.63 -> 1.625

.deployedprotoversion, .github/workflows/deploy.yml, sim/core/TestProtoVersioning.results
This PR updates our `build-and-deploy` GitHub Actions workflow to copy the `TestProtoVersioning.results` file into a `.deployedprotoversion` reference file before running tests, and to automatically push this file to `master` if the version number was incremented in the merge commit that triggered the workflow. These two files are not currently used for anything, but are required for the proto versioning unit test that was added to #866 . I am PRing the workflow change separately from #866 in order to test that the workflow is functioning properly before finalizing the new unit test in #866 .
=> Update API version in build-and-deploy workflow

.github/workflows/deploy.yml
#869 did not deploy because direct pushes to `master` are not permitted. This is an attempted fix, which creates a PR for the changed version file rather than directly pushing it.
=> Versioning workflow fix

.github/workflows/deploy.yml
#872 did not deploy since the PR could not be created, even though it deployed just fine with default permissions. This is an attempted fix by explicitly adding the "pull-requests: write" permission to the config.
=> Add "pull-requests: write" permission to build-and-deploy workflow.

ui/core/components/suggest_reforges_action.tsx
Prunes reforges whose destination stats aren't in the spec's EP stats.
Improves Suggest Reforge runtime on Combat Rogue sim from 54 seconds to 26 seconds in Edge.
=> Don't generate variables for reforges of zero EP stats

.github/workflows/release.yml
This should ensure that `npm install` is run before `make tests`, since `npx buf` is called in one of the unit tests after the proto versioning update. 
On branch versioning_workflow
modified:   .github/workflows/release.yml
=> Swap build and test order in release workflow

ui/core/components/importers.tsx
Since the exporter adds the version to the equipment the importer would break since the proto would try to parse the version tag
=> Remove version before adding to equipmentspec proto

sim/common/cata/stat_bonus_stacking.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/unholy/TestUnholy.results, sim/paladin/retribution/TestRetribution.results, sim/paladin/seal_of_truth.go, sim/priest/shadow/TestShadow.results
[License to Slay](https://www.wowhead.com/cata/item=58180/license-to-slay) has the `Can Proc From Procs` mask just like [Tiny Abomination in a Jar](https://www.wowhead.com/cata/item=50706/tiny-abomination-in-a-jar) which means it should proc from some more stuff than just melee attacks, like the application of Paladins Censure-dot.
This PR changes the proc mask to reflect that on the trinket as well as fixing the proc mask for Censure application which in turn means it shouldn't proc enchants (Landslide, Tailoring etc.) and not cause an over exaggerated amount of procs of other trinkets like [Darkmoon Card: Hurricane](https://www.wowhead.com/cata/item=62049/darkmoon-card-hurricane)
=> [Ret] Fix Censure application and License to Slay proc masks

sim/priest/items.go, sim/priest/shadow/TestShadow.results
Adds set effects for the T12 set for shadow priests.
**2P**: `While you are in Shadowform, your Shadowfiend deals 20% additional damage as Fire damage and its cooldown is reduced by 75 sec.`
**4P**: `While you have Shadow Word: Pain, Devouring Plague, and Vampiric Touch active on the same target you gain Dark Flames, which increases the damage done by Mind Blast by 15%.`
=> [Priest] Add shadow T12 set

sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warlock/doomguard.go
When plotting breakpoints and stat scaling I found out that Doomguard has massive peaks at certain fixed haste breakpoints. After some digging together with Ketesh, TheNameLess and Malvanis in the Warlock Discord we found that it is related to Doomguard gaining a extra cast.
The fixed 400ms cast delay is however not "game like" and should be changed. I've analysed 1700+ Doomguard casts in logs and created the following Histogram highlighting a more accurate interpretation:
We came to the consensus to set the cast delay to a random number between 150 and 750ms.
**Results**
**Stat scaling**
Before: https://docs.google.com/spreadsheets/d/e/2PACX-1vSOhHz6EmXS4SOdfz8MCdXkx9jzOP0_7yhGreE_HeUIjSjxdXv3rMXLYacYfwEWudM3cA00O1ndgc4Z/pubchart?oid=1571781985&format=interactive
After: …
=> [WARLOCK] Add random cast delay to Doomguard

ui/core/components/character_stats.tsx, ui/core/components/suggest_reforges_action.tsx, ui/warlock/affliction/sim.ts, ui/warlock/demonology/sim.ts
- Added initial Mastery rounding offset of 0.60% to Demo breakpoints table
- Changed breakpoints overview table to include Mastery skill % instead of points
**Current**
**Fixed**
Matches table from Discord:
=> [WARLOCK][DEMO] Fix Mastery flooring breakpoints

ui/core/components/suggest_reforges_action.tsx, ui/warlock/affliction/sim.ts, ui/warlock/demonology/sim.ts
- Fix visual representation of Mastery breakpoints
- Undo "fix" (skill issue)
=> [WARLOCK] Visual Mastery breakpoints

sim/mage/combustion.go, sim/mage/living_bomb.go
resolves the issue where dot crit chance is a lot lower than the explosion:
caused by hit count to be incremented when the dot is applied
=> fix dot mage crit metrics

ui/core/components/raid_sim_action.tsx, ui/scss/core/components/_detailed_results.scss, ui/scss/core/components/detailed_results/_topline_results.scss
- Make topline results equally-sized
- Removed bottom border from topline results
- Center all results header `th`s (matches how WCL does it as well)
- Removed an extra `padding-right: 10px` that was causing the topline results to be misaligned on the right side of the screen
=> Small style tweaks on results refactor

sim/warlock/demonology/demonology.go, sim/warlock/summon_demon.go, sim/warlock/talents_demonology.go, ui/warlock/destruction/apls/default.apl.json
- Resolves https://github.com/wowsims/cata/issues/927
- Add a guard to prevent errors when the warlock doesn't have a pet selected in settings
- Resolves https://github.com/wowsims/cata/issues/917
- Impending doom CD reduction should only be initialized if also using the Metamorphosis talent
- Update Destro APL to handle not using T11 4pc "Fel Spark"
=> [Warlock] Fix errors when no warlock pet selected in settings

ui/core/components/detailed_results/damage_metrics.tsx, ui/core/components/detailed_results/dtps_metrics.tsx, ui/core/components/detailed_results/healing_metrics.tsx, ui/core/components/detailed_results/metrics_table/metrics_combined_tooltip_table.tsx
The minifier assumes that this function that's not assigned is dead code thus removes it in production builds.
=> [FIX] Minification issue

ui/druid/balance/sim.ts, ui/priest/shadow/sim.ts, ui/shaman/elemental/sim.ts
On branch stats_refactor
modified:   ui/druid/balance/sim.ts
modified:   ui/priest/shadow/sim.ts
modified:   ui/shaman/elemental/sim.ts
=> Display Spirit as Hit Rating for hybrid casters

sim/core/consumes.go, sim/encounters/bwd/magmaw_ai.go
- Fixed a bug where Tank 2 was taking the first Mangle rather than the second on Magmaw Heroic presets, leading to unrealistic damage intake on fast kills.
- Added simulated tank swaps to Normal mode Magmaw presets in order to match Heroic behavior. This fixes an unintuitive result where survival rates were lower on Normal than Heroic, since the Normal mode agent was tanking Magmaw the entire time even with the Sweltering Armor debuff.
- Implemented missing Alchemy bonus for Stamina flasks and Battle Elixirs.
=> Tank Fixes

sim/core/spell_result.go, ui/core/proto_utils/logs_parser.tsx
- Added missing `SpellFlagNoLogs` checks
- Changed how the logs parser displays heals
=> [UI][FIX] Displayed healing hits

sim/death_knight/frost/TestFrost.results, sim/priest/mind_sear.go, sim/priest/shadow/TestShadow.results, sim/priest/shadow/shadow.go
* Implements proper mastery flooring for `Empowered Shadows`
* Implements proper mastery flooring for `Shadow Orb`
* Refactor for Mind sear to deal AoE damage for each channel cast instead of creating a cast for each target per channel tick
=> [Priest] Fixes for Mastery and Sear refactor

sim/core/buffs.go, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, ui/paladin/retribution/sim.ts
Replenishment was changed from 1% per 5sec to 1% over 10sec in cata but this was never reflected in code.
If one would be pedantic, it should be 0.1% per second but adding that many events is probably a perf degradation. The downside to having it as mp5 is that it's not trackable in the resource breakdown, and specs like Ret which *technically* run oom for ~0.1-0.2s probably wouldn't if mana ticked continuously (I think, who knows).
=> Replenishment fix

sim/core/aura_helpers.go, sim/core/unit.go, sim/druid/druid.go, sim/druid/feral/TestFeral.results, sim/druid/feral/feral.go, sim/druid/feral/feral_test.go, sim/druid/feral/rotation.go, sim/druid/rake.go, sim/druid/rip.go
Generalizes the existing analytical logic used for clipping Rip situationally to snapshot Tiger's Fury (when doing so is a net DPE gain), and applies it to arbitrary temporary bleed power buffs implemented via TemporaryStatsAura helpers. Also applies the same logic to Rake snapshotting.
Net DPS impacts of this PR under default settings:
P1 gear, mono-cat talents = +142 DPS
P1 gear, hybrid talents = +85 DPS
P3 gear, mono-cat talents = +52 DPS
P3 gear, hybrid talents = +127 DPS
=> Generalized Feral bleed snapshotting algorithm

proto/common.proto, proto/warlock.proto, sim/warlock/demonology/demonology.go, sim/warlock/demonology/metamorphosis.go, ui/core/proto_utils/action_id.ts, ui/warlock/demonology/presets.ts, ui/warlock/demonology/sim.ts, ui/warlock/inputs.ts
- Allows to adjust mana after swapping from prepull set
- Added UI for post prepull mana
- Added OtherID for Prepull specific actions
=> [DEMONOLOGY][UI] Add post prepull snapshot mana

sim/core/runic_power.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/items.go, sim/death_knight/unholy/TestUnholy.results
- Add `AddUnscaledRunicPower` for adding non-scaling runic power to prevent updating the multiplier every tick
- Remove the modifiers flag from Blood T12 Burning Blood spell until we have proof only CoE like abilities affect it.
=> [DK] Minor T12 implementation fixes

ui/core/constants/item_notices.tsx
- Added warning for items that never existed (taken from: https://www.wowhead.com/cata/items/min-level:391/max-level:391/quality:4?filter=128:17;2:1204;0:0)
- Added warning for items that are missing their Armor stat value (taken from: https://wago.tools/db2/ItemSparse?build=4.4.1.56574&filter[InventoryType]=1%7C3%7C5%7C6%7C7%7C8%7C9%7C10%7C14%7C16%7C20&filter[OverallQualityID]=exact%3A4&filter[Bonding]=1&filter[Resistances_0]=exact%3A0&page=1&sort[ID]=asc)
=> [UI] Add non existing items and missing armor value warning

sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/protection/protection.go, ui/warrior/protection/sim.ts
- Sentinel has a fixed 15% block, not multiplicative
- Added Toughness to be included in the UI's Armor values
=> [WARRIOR][UI] Fix Prot block percent & add toughness to UI stats

sim/mage/arcane/TestArcane.results, sim/mage/arcane/arcane.go
When testing VPLC on PTR the damage was way off for Arcane. Investigating this anomaly we figured out that Mana Adept has a Class Mask present that should most likely not be there: https://wago.tools/db2/SpellEffect?build=4.4.1.56574&filter[SpellID]=76547&page=1 (all 0)
This fix brings the VPLC damage much closer to what was found in logs we aquired.
=> [MAGE][ARCANE] Remove Mana Adept class mask

sim/common/cata/other_effects.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/balance/TestBalance.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results, ui/core/constants/item_notices.tsx
Adds the following trinkets from #902:
- [Jaws of Defeat](https://www.wowhead.com/cata/item=68926/jaws-of-defeat)
- [Jaws of Defeat Heroic](https://www.wowhead.com/cata/item=69111/jaws-of-defeat)
- [Spidersilk Spindle](https://www.wowhead.com/cata/item=68981/spidersilk-spindle)
- [Spidersilk Spindle Heroic](https://www.wowhead.com/cata/item=69138/spidersilk-spindle)
- [Scales of Life](https://www.wowhead.com/cata/item=68915/scales-of-life)
- [Scales of Life Heroic](https://www.wowhead.com/cata/item=69109/scales-of-life) 
- [Stay of Execution](https://www.wowhead.com/cata/item=68996/stay-of-execution)
[Eye of Blazing Power](https://www.wowhead.com/cata/item=68983/eye-of-blazing-power) and [Eye of Blazing Power Heroic](https://www.wowhead.com/cata/item=69149/eye-of-blazing-power) marked …
=> Add missing trinket implementations

sim/druid/feral/rotation.go
- Lowered Primal Madness cancellation threshold for normal TF windows from 20e to 14e to account for the effective Energy cost of losing a final TF-buffed Shred at the very end of the window due to an early cancellation.
- Re-enabled Primal Madness cancellation during Berserk with a 0 Energy threshold, matching the same logic for the correction term applied to cancellations during TF windows.
- Net DPS impacts of this PR under default settings: P1 BiS = +115 DPS, P3 loot priority reference = +129 DPS, P3 BiS = +73 DPS
=> Feral Rotation Updates

ui/core/components/individual_sim_ui/cooldowns_picker.ts, ui/core/player.ts, ui/druid/feral/sim.ts
On branch hide-mcds
modified:   ui/core/components/individual_sim_ui/cooldowns_picker.ts
modified:   ui/core/player.ts
modified:   ui/druid/feral/sim.ts
=> Allow specs to selectively hide MCDs from the Simple Cooldowns UI

ui/core/components/pickers/dropdown_picker.tsx
Code would never apply Bootstrap dropdown properties if `buttonElem` was already defined.
=> [UI] Fix dropdowns not showing if buttonElem is defined

sim/core/runic_power.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/death_strike.go
[Blood Rites](https://www.wowhead.com/cata/spell=50034/blood-rites) was not added to Death Strike, only Obliterate. Seeing as DS isn't refunded on miss/dodge/parry it has to be handled a little differently!
=> [Blood] Convert death runes for DS

sim/common/cata/other_effects.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/balance/TestBalance.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/elemental/TestElemental.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
Every trinket was using the highest rank (the last value in the loop) for all aura ids, stat values etc 🤦 thanks to some fun scoping issues
=> Fix block scoping for item version variable

sim/common/cata/other_effects.go, sim/common/cata/stat_bonus_stacking.go, sim/death_knight/frost/TestFrost.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/items.go, sim/warrior/protection/TestProtectionWarrior.results
Fixes #1112 
Fixes #1116 
* [Warrior] Use shared ignite helper for Prot T12 2pc
* [Warrior] Use melee hit table for DPS T12 4pc
* Add some blacklisted abilities to Vessel of Acceleration
* Slam OH
* Whirlwind OH
* Add some blacklisted abilities to Apparatus of Khaz'goroth
* Warrior
* Raging Blow (MH and OH)
* Whirlwind (OH) 
* Death Knight
* Any strike triggered by Threat of Thassarian (all kinds of OH crits)
=> Some trinket and T12 fixes after PTR testing

proto/ui.proto, ui/core/components/suggest_reforges_action.tsx, ui/core/individual_sim_ui.tsx, ui/core/player.ts, ui/core/proto_utils/stats.ts, ui/mage/fire/sim.tsx
- Add the ability to let the user choose to override to a max breakpoint limit
- Example: A Mage would like to have more control over which breakpoint should be the cap (15%, 20% etc), to go a bit more Crit heavy. The stat cap flow doesn't work for that due to 0-ing the EP after reaching a cap.
- Dropdown is based on the available options defined by the Sim
=> Add ability to limit breakpoint capping

sim/common/cata/gurthalak.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/death_knight.go, sim/death_knight/frost/TestFrost.results, sim/death_knight/talents_unholy.go, sim/death_knight/unholy/TestUnholy.results, sim/death_knight/unholy/unholy.go, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/paladin/paladin.go, sim/paladin/retribution/TestRetribution.results, sim/rogue/combat/TestCombat.results, sim/rogue/combat/combat_test.go, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/fury/death_wish.go, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/protection/protection_test.go, sim/warrior/warrior.go, ui/core/constants/item_notices.tsx, ui/core/proto_utils/action_id.ts
Tried to replicate all the EJ-, Wowhead- and Simc-comments I could gather.
Damage matches all the videos of the different versions of the sword on YouTube, including which buffs increase the proc damage.
Had to modify Unholy mastery to apply to all shadow damage and move the SpellMod to only modify Unholy Blight and Scourge Strike off-hand since they had IgnoreAllModifiers.
Also made a change to Death Wish for Fury Warriors since it's only supposed to increase physical damage, changes most tests a big seeing as it appeared to modify the T12 fire-proc.
I've been restrictive with the proc mask for now and skipped the `Can Proc From Procs` flag, it's there in the db but it already pretty much matches the expected numbers.
The rest has to be tested on the PTR :)
Left lot's of TODOs for future …
=> Add Gurthalak, Voice of the Deeps

sim/mage/arcane/TestArcane.results, sim/mage/arcane/dragonwrath.go
Go's untyped constants "feature" at its best...
> if the operands of a binary operation are different kinds of untyped constants, the operation and, for non-boolean operations, the result use the kind that appears later in this list: integer, rune, floating-point, complex.
```
1/12 == 0
1.0/12 == 0.0833...
1/12.0 == 0.0833...
1.0/12.0 == 0.0833...
```
=> [Arcane] Fix DTR proc rate for arcane

sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/mage/mirror_image_t12.go, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warlock/items.go
- Adjusted the MI base crit, inherited crit and crit damage modifier
- See screenshot for matches
- Adjusted Warlock Fiery Imp crit damage modifier
- https://docs.google.com/spreadsheets/d/12jnHZgMAYDTBmkeFjApaHL5yiiDlxXHYDbTXy2QCEBA/edit?gid=1677205971#gid=1677205971
**Crit set to 2.0**
**Crit set to 1.5**
=> [Mage] Adjust T12 MI crit chance

ui/core/encounter.ts, ui/core/individual_sim_ui.tsx, ui/druid/feral/presets.ts, ui/hunter/beast_mastery/presets.ts, ui/hunter/marksmanship/presets.ts, ui/hunter/survival/presets.ts, ui/paladin/retribution/presets.ts, ui/rogue/assassination/presets.ts, ui/rogue/combat/presets.ts, ui/rogue/subtlety/presets.ts, ui/shaman/elemental/presets.ts, ui/shaman/enhancement/presets.ts, ui/warlock/affliction/presets.ts, ui/warlock/demonology/presets.ts, ui/warlock/destruction/presets.ts
On branch unify-fight-length
modified:   ui/core/encounter.ts
modified:   ui/core/individual_sim_ui.tsx
modified:   ui/druid/feral/presets.ts
modified:   ui/hunter/beast_mastery/presets.ts
modified:   ui/hunter/marksmanship/presets.ts
modified:   ui/hunter/survival/presets.ts
modified:   ui/paladin/retribution/presets.ts
modified:   ui/rogue/assassination/presets.ts
modified:   ui/rogue/combat/presets.ts
modified:   ui/rogue/subtlety/presets.ts
modified:   ui/shaman/elemental/presets.ts
modified:   ui/shaman/enhancement/presets.ts
modified:   ui/warlock/affliction/presets.ts
modified:   ui/warlock/demonology/presets.ts
modified:   ui/warlock/destruction/presets.ts
=> Standardize default fight length across sims

sim/core/dot.go, sim/warrior/arms/TestArms.results, sim/warrior/arms/talents.go, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/rend.go, sim/warrior/talents.go
rend ticking on mortal strike/thunder clap refreshes was fixed with the new patch.
old:
new:
=> fix warrior rend ticking and "snapshot" behavior

sim/common/cata/stat_bonus_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/frost/frost_test.go, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/enhancement/TestEnhancement.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results, ui/core/launched_sims.ts, ui/death_knight/frost/apls/2h.apl.json, ui/death_knight/frost/apls/dw.apl.json, ui/death_knight/frost/apls/masterfrost.apl.json, ui/death_knight/frost/gear_sets/p1.2h.gear.json, ui/death_knight/frost/gear_sets/p1.dw.gear.json, ui/death_knight/frost/gear_sets/p1.masterfrost.gear.json, ui/death_knight/frost/gear_sets/p3.masterfrost.gear.json, ui/death_knight/frost/gear_sets/prebis.gear.json, ui/death_knight/frost/presets.ts, ui/death_knight/frost/sim.ts, ui/death_knight/unholy/apls/default.apl.json
* [[Frost] Move Frost Death Knight to phase 3](https://github.com/wowsims/cata/pull/1149/commits/4658203ae6a713225a4561c6f2a231a11f17530a)
* Updated presets
* Updated ep weights
* Updated APLs with support for normal versions of Heart of Solace, Heart of Rage, Crushing Weight and Apparatus as well as the horde/alliance versions of Impatience of Youth
* [[Item] Fix outcome flag for normal Heart of Solace](https://github.com/wowsims/cata/pull/1149/commits/39a4cf9cc525c4d19119d437ac6e2f1872f3ed4b)
* Was copy-pasted wrong to be "on parry" instead of "on hit" 🙈 
* [[Unholy] Update APL with support for normal version of trinkets](https://github.com/wowsims/cata/pull/1149/commits/1b916e377dae4fb8a66e0a61144942e014c06043)
* Added support for normal version of Heart of Solace and Heart of Rage
=> [DK] Move Frost Death Knight to phase 3 and fix APL for normal trinkets

sim/common/cata/stat_bonus_procs.go, sim/common/shared/shared_utils.go, sim/core/apl_values_aura_sets.go, sim/core/aura_helpers.go, sim/shaman/elemental/TestElemental.results, sim/warlock/demonology/TestDemonology.results
Currently only affects the Sorrowsong trinket.
=> Blacklist proc trinkets with extra proc conditions from APL aura sets

sim/core/pet.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/ghoul_pet.go, sim/death_knight/raise_dead.go
Emulate the DK Raise Dead doing its RP "climbing out of the ground" thing.
The lowest I saw on logs was 4.5s and the longest around 5s, all depending on how far the Ghoul had to walk after summon.
=> [DK] Add delay to Raise Dead start attack

sim/death_knight/death_coil.go
It should always target the Ghoul 🙈 and do nothing if added to any other spec than UH
=> [Unholy] Fix target of prepull Death Coil and make it Unholy only

sim/death_knight/blood_strike.go, sim/death_knight/death_knight.go, ui/core/proto_utils/action_id.ts
By popular (ish) demand, for APL minmaxing shenanigans.
=> [DK] Add Blood Strike

ui/core/components/gear_picker/gear_picker.tsx, ui/core/components/item_notice/item_notice.tsx, ui/core/constants/item_notices.tsx
- Added `additionalNoticeData` to manually add custom fields that might be context dependent
=> Allow addition of manual item notices

ui/core/components/suggest_reforges_action.tsx
Changed timeout condition for Suggest Reforges LP solver from time-based (10s) to iteration-based (100k). This allows a partially converged solution to still be found even on low performance browsers (Firefox) - the solve will just take a lot longer compared to better browsers.
=> Suggest Reforges timeout fix for Firefox

sim/hunter/beast_mastery/TestBM.results, sim/hunter/cata_items.go, sim/hunter/marksmanship/TestMM.results, sim/hunter/serpent_sting.go, sim/hunter/survival/TestSV.results, sim/hunter/survival/black_arrow.go, sim/hunter/survival/explosive_shot.go, ui/core/components/detailed_results/timeline.tsx, ui/core/proto_utils/action_id.ts, ui/hunter/survival/gear_sets/preraid_sv.gear.json, ui/hunter/survival/presets.ts, ui/hunter/survival/sim.ts
- Fix Black Arrow, Serpent Sting and Explosive Shot snapshotting ticks
- Fix Explosive Shot having wrong crit damage multiplier (2.09 instead of 2.06)
- Fix T12 4-set being consumed by things it shouldn't be consumed by
- Clean up Survival presets
=> Various survival fixes and T12 fix

sim/core/character.go, sim/core/consumes.go
Popping the Mana/Healing potions using Tinkers would not put the potion on CD, allowing some specs like Arcane Mage benefit from this greatly.
=> Add global potion timer to fix Tinker potions

sim/warrior/arms/TestArms.results, sim/warrior/protection/TestProtectionWarrior.results, sim/warrior/rend.go
The damage formula for Rend was a bit off, it was copied from the tooltip which has a 6x multiplier in it that shouldn't be there. In this case, that `*6` in the tooltip should in fact be a 5 since it's the tick count (tooltip does show total damage over 15sec).
Sim also used the rounded, final value from the tooltip instead of using the class scaling coefficient and spell effect avg.
Compared from a guildies log and his exact gear imported to the sim with the same buffs and found a place where no extra AP modifiers or other stuff was active.
Sorry for nerfing but all is as it should be 😆
=> [Warrior] Fix Rend damage formula

sim/shaman/enhancement/TestEnhancement.results, ui/shaman/enhancement/gear_sets/p1.non-orc.gear.json, ui/shaman/enhancement/gear_sets/p1.orc.gear.json, ui/shaman/enhancement/gear_sets/p3.non-orc.gear.json, ui/shaman/enhancement/gear_sets/p3.orc.gear.json, ui/shaman/enhancement/gear_sets/preraid.gear.json
For some reason, Chaotic was used in all presets when Agile is consistently better by 140-150dps 🤷
=> [Enha] Use correct Agile meta instead of Chaotic

ui/core/components/individual_sim_ui/apl_values.ts, ui/core/components/pickers/list_picker.tsx, ui/scss/core/components/_list_picker.scss, ui/scss/core/components/individual_sim_ui/_apl_rotation_picker.scss, ui/scss/shared/_global.scss
Doing a ton of APL editing highlighted a few missing features that would really speed things up, so I added them!
* Drag and drop APL values inside an `Any of` / `All of`
* Not restricted to the same list, can be moved in/out any number of levels **and even between different APL actions**
* Being able to copy an APL value inside an `Any of` / `All of`
* Clearer indication of what block will be deleted inside nested `Any of` / `All of`
* Having the whole block show up as the drag-placeholder instead of just the move-button
Any feedback is appreciated!
https://github.com/user-attachments/assets/20f6edd3-4b19-4cfd-bee7-7a4b00f79ddf
=> [UI] Improve drag-and-drop support in APL editor

ui/core/components/pickers/list_picker.tsx
* Fixed a bug where you could accidentally drop *inside* a child of it's own, making it disappear 🙈 
* Added some logic to determine if we should drop before or after the current target
* Move the dragged element more to the right, to not interfere with the cursor at all
=> [UI] Drag and drop fixes

ui/core/talents/glyphs_picker.tsx, ui/core/talents/mage.ts
Had a special case fix for Glyph of Fireball before since the item tooltip says 5% damage but the spell shows the correct 5% crit. This PR just does this for *all* glyphs across the board, to never show "empty" tooltips.
Old:
New:
=> [UI] Always show spell tooltip instead of glyph item tooltip

proto/api.proto, ui/core/cache_handler.ts, ui/core/components/detailed_results.tsx, ui/core/components/detailed_results/log_runner.tsx, ui/core/components/detailed_results/metrics_table/metrics_table.tsx, ui/core/components/detailed_results/player_damage.tsx, ui/core/components/detailed_results/player_damage_taken.tsx, ui/core/components/detailed_results/resource_metrics.tsx, ui/core/components/detailed_results/result_component.ts, ui/core/components/detailed_results/results_filter.ts, ui/core/components/detailed_results/timeline.tsx, ui/core/components/individual_sim_ui/apl_helpers.tsx, ui/core/components/raid_sim_action.tsx, ui/core/components/results_viewer.tsx, ui/core/constants/lang.ts, ui/core/proto_utils/logs_parser.tsx, ui/core/proto_utils/sim_result.ts, ui/core/sim.ts, ui/core/utils.ts, ui/core/worker_pool.ts, ui/scss/core/components/detailed_results/_timeline.scss
- Added the request ID to the raid sim request to have a unique value to build cache keys with
- Added a generic CacheHandler to allow for caching of elements that do not change and can be reused.
- Added caching to diverse "enriched" HTML Nodes that are dependent on async calls like wowhead datasets
- Added caching (max 2 entries) to SimResults to make toggling between 2 (reference) datasets much quicker
- Added caching to the Timeline content
- Fixed DPS graph Timeline tooltips
**After & Before**
~ 3x performance increase when swapping/toggling between 2 results
Overall GC improvement
=> [UI] Feature/improve detailed results performance

sim/core/energy.go, sim/core/focus.go, sim/death_knight/unholy/TestUnholy.results, sim/hunter/beast_mastery/TestBM.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results
On branch feature/add-trinket-swapping
modified:   sim/core/energy.go
modified:   sim/core/focus.go
modified:   sim/rogue/combat/TestCombat.results
modified:   sim/rogue/subtlety/TestSubtlety.results
=> Keep Energy and Focus tick randomized during reset actions.

sim/warlock/demonology/TestDemonology.results, ui/warlock/demonology/gear_sets/p3.gear.json, ui/warlock/demonology/presets.ts, ui/warlock/demonology/sim.ts
- Will now properly always prio Haste > Mastery, unless wasting a stat such as Hit in the process by over capping
- Added prepull mastery values as that is now the standard
=> Adjust breakpoint calculation for Demo P3

sim/common/cata/stat_bonus_procs.go, sim/death_knight/unholy/TestUnholy.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/cata_items.go, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/rogue/combat/TestCombat.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warlock/items.go, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
This is a benign PR that simply changes a few RNG seed labels for set bonuses to match the refactors in #1253 , so that we can more clearly assess any true results changes caused by #1253 .
=> Set bonus RNG seed labeling change

sim/rogue/assassination/TestAssassination.results, sim/rogue/assassination/vendetta.go
Merging separately from #1253 for a cleaner final unit test comparison in #1253 .
=> Fix Rogue 4pT13 to correctly add 9s to Vendetta duration

proto/warlock.proto, sim/core/apl.go, sim/shaman/elemental/TestElemental.results, sim/shaman/elemental/elemental_test.go, ui/warlock/demonology/inputs.ts, ui/warlock/demonology/sim.ts, ui/warlock/inputs.ts
- Added prepull Mastery using Item Swap bonus stats
=> Add back prepull Mastery for secondary trinket swaps during swapped prepull

sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/feral/apl_values.go, sim/druid/feral/feral.go, sim/druid/feral/rotation.go
Fixed a bug in Feral rotational logic where the agent would occasionally initiate a leave-weave when there was insufficient Energy to cast Feral Charge.
modified:   sim/druid/feral/apl_values.go
modified:   sim/druid/feral/feral.go
modified:   sim/druid/feral/rotation.go
=> [Feral] Add Energy check for initiating leave-weaves

proto/common.proto, sim/core/armor_test.go, sim/core/buffs.go, sim/core/debuffs.go, sim/warrior/glyphs.go, sim/warrior/shattering_throw.go, ui/core/components/inputs/buffs_debuffs.ts, ui/core/proto_utils/action_id.ts, ui/core/talents/warrior.ts, ui/scss/core/components/_icon_picker.scss
- Add (enable) Shattering Throw as Buff (external)
- Added Shattering Throw Missile Speed
- Modified Action ID for self and raid casts
- Modified Faerie Fire (external) to always apply 3 stacks as if it's cast by a Feral Druid
- Removed Glyph of Shattering Throw
=> Add Shattering Throw raid buff

sim/druid/balance/TestBalance.results, sim/druid/talents.go, ui/druid/balance/sim.ts
Fixed a bug where Nature's Majesty was boosting the Crit chance of Feral melee abilities.
modified:   sim/druid/balance/TestBalance.results
modified:   sim/druid/talents.go
modified:   ui/druid/balance/sim.ts
=> Nature's Majesty Bug Fix

sim/core/aura_helpers.go, sim/core/character.go, sim/druid/druid.go, sim/druid/feral/feral.go, sim/druid/forms.go, sim/druid/guardian/tank.go, sim/druid/talents.go
I finally figured out how to refactor things so that stat buffs + stat dependencies associated with a Druid form Aura can be applied during the appropriate character build phase for each effect. As a result, stat contributions in the UI stats display for the Feral and Guardian sims finally add up to the total value. This does come at a small performance cost due to chaining multiple callbacks for the form Auras vs. evaluating all effects in one function.
=> [Feral] Talents Code Refactor

sim/common/cata/other_effects.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/paladin/protection/TestProtection.results, sim/paladin/retribution/TestRetribution.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/enhancement/TestEnhancement.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
modified:   sim/common/cata/other_effects.go
modified:   sim/death_knight/blood/TestBlood.results
modified:   sim/death_knight/frost/TestFrost.results
modified:   sim/druid/guardian/TestGuardian.results
modified:   sim/hunter/marksmanship/TestMM.results
modified:   sim/hunter/survival/TestSV.results
modified:   sim/paladin/protection/TestProtection.results
modified:   sim/paladin/retribution/TestRetribution.results
modified:   sim/rogue/assassination/TestAssassination.results
modified:   sim/rogue/combat/TestCombat.results
modified:   sim/rogue/subtlety/TestSubtlety.results
modified: …
=> Add AP scaling to Vial of Shadows based on PTR testing

sim/druid/feral/TestFeral.results, sim/druid/feral/rotation.go
- Remove rotational blocker on Berserk when a Stampede proc is active. This sims as a wash for pre-P4 setups but has a substantial impact on 4pT13 setups.
- Delay TF usage in 4pT13 setups if a Stampede proc is already active. Minor impact but included for thoroughness.
Net DPS impacts of this PR under default conditions:
```
Pre-Raid, Mono-Cat: +1.3 DPS
P3, Mono-Cat: -0.1 DPS
P4, Mono-Cat: +585 DPS
P4, Hybrid: +473 DPS
P3, Hybrid: -1.6 DPS
Pre-Raid, Hybrid: +0.5 DPS
```
=> Feral 4pT13 Rotation Adjustments

sim/common/cata/dragonwrath.go, sim/core/spell_mod.go, sim/druid/balance/TestBalance.results, sim/druid/balance/dragonwrath.go, sim/shaman/elemental/TestElemental.results, sim/shaman/elemental/dragonwrath.go
Discussed this with InDebt, Exesian and Polynomix:
- Mushrooms can only proc once, but the proc "roll" is done for each target until it either didn't proc, or found 1 proc.
- Currently each duplicated shroom can in theory dupe for each target (3x3x3), which is not how it should be.
- Applied same logic to Fire Nova (seems to be AOE flagged as the proc rate is much lower)
=> Implement findings

sim/core/gcd.go, sim/core/pending_action.go, sim/druid/feral/apl_values.go, sim/druid/feral/feral.go, sim/druid/feral/pooling_actions.go, sim/druid/feral/rotation.go, sim/rogue/combat/TestCombat.results, sim/rogue/combat/killing_spree.go, sim/web/main.go
When profiling melee sim runs, I observed that a considerable amount of overhead is spent on creating new `PendingAction` structs each time the rotation action is rescheduled (either after a cast, or after a wait call, etc.). This PR should make it safe to re-use cancelled `PendingAction` structs by removing them from the sim queue automatically during calls to `Cancel()`.
=> Re-use rotation action instead of re-allocating

ui/core/individual_sim_ui.tsx
Fully remove bulk sim tab for the time being, until the intermittent memory leak with the Calculate Combos request is resolved.
On branch batch
modified:   ui/core/individual_sim_ui.tsx
=> Fully remove bulk sim tab for the time being

sim/priest/shadow/TestShadow.results, sim/priest/talents.go
- Verified TD and TF affect non-Priest spells such as Darkmoon Card: Death and Cunning of the Cruel
=> Remove TD and TF Priest Spell Masks

ui/druid/guardian/sim.ts
Dynamically adjust post-cap EP for Expertise Rating based on pre-cap value.
On branch guardian
modified:   ui/druid/guardian/sim.ts
=> [Guardian] Dynamically adjust post-cap EP for Expertise Rating

proto/apl.proto, sim/core/apl_action.go, sim/core/apl_actions_casting.go, ui/core/components/individual_sim_ui/apl_actions.ts
- Will cast all Dots to given targets in a strict sequence, not interrupting casting. (e.g. Useful for Boomkin when you don't want to desync application of Dots)
- Will check for previous Dots and offset a potential GCD/Cast time difference to account for re-casting.
=> [APL] Strict multidotting

ui/rogue/combat/presets.ts
no test or armor set adjustments. This is a EP set for No'Kaled which isn't bis, but is _very_ good on the way to oranges.
=> [Combat] Panic increase spell hit EP after recent sim adjustments

sim/rogue/assassination/TestAssassination.results, sim/rogue/assassination/assassination.go, sim/rogue/assassination/vendetta.go, sim/rogue/combat/TestCombat.results, sim/rogue/combat/bandits_guile.go, sim/rogue/combat/combat.go, sim/rogue/combat/killing_spree.go, sim/rogue/rogue.go, ui/core/launched_sims.ts, ui/rogue/assassination/sim.ts, ui/rogue/combat/sim.ts, ui/rogue/subtlety/sim.ts
Previously these effects multiplied all damage, including procs like No'Kaled and Vial of Shadows. This has been found to be inaccurate. I suspect there may be other damage multipliers like this lurking in other specs, might need a focused sweep of all modifiers like these.
=> [Rogue] Fix for Bandit's Guile/Vendetta Class Mask Damage Multiplier, + cosmetic updates

sim/common/cata/other_effects.go, sim/common/cata/stat_bonus_procs.go, sim/core/character.go, sim/core/constants.go, sim/druid/balance/TestBalance.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/mage/fire/TestFire.results, sim/priest/shadow/TestShadow.results, sim/shaman/elemental/TestElemental.results
- Fixes TikTok staff pro conditions
- Fixes issue where Armor Spec was not being applied when having empty slots (Useful to have fixed for scaling testing when not having full item sets equipped)
=> Fix Armor Spec check and tiktok staff proc condition

sim/common/cata/stat_bonus_procs.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/death_knight/unholy/TestUnholy.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/mage/arcane/TestArcane.results, sim/paladin/protection/TestProtection.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results, sim/rogue/assassination/TestAssassination.results, sim/rogue/combat/TestCombat.results, sim/rogue/subtlety/TestSubtlety.results, sim/shaman/enhancement/TestEnhancement.results, sim/warrior/arms/TestArms.results, sim/warrior/fury/TestFury.results, sim/warrior/protection/TestProtectionWarrior.results
On branch bugfix/fix-procs
modified:   sim/common/cata/stat_bonus_procs.go
modified:   sim/death_knight/blood/TestBlood.results
modified:   sim/death_knight/frost/TestFrost.results
modified:   sim/druid/guardian/TestGuardian.results
modified:   sim/hunter/marksmanship/TestMM.results
modified:   sim/hunter/survival/TestSV.results
modified:   sim/mage/arcane/TestArcane.results
modified:   sim/paladin/protection/TestProtection.results
modified:   sim/paladin/retribution/TestRetribution.results
modified:   sim/priest/shadow/TestShadow.results
modified:   sim/rogue/assassination/TestAssassination.results
modified: …
=> Fix incorrect proc data for The Hungerer (H) and Idol of Battle trinkets

sim/common/cata/enchant_effects.go, sim/death_knight/unholy/TestUnholy.results, sim/druid/balance/TestBalance.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/hunter/survival/TestSV.results, sim/paladin/protection/TestProtection.results, sim/paladin/retribution/TestRetribution.results, sim/priest/shadow/TestShadow.results
On branch bugfix/fix-procs
modified:   sim/common/cata/enchant_effects.go
modified:   sim/druid/balance/TestBalance.results
modified:   sim/hunter/marksmanship/TestMM.results
modified:   sim/hunter/survival/TestSV.results
modified:   sim/paladin/protection/TestProtection.results
modified:   sim/paladin/retribution/TestRetribution.results
modified:   sim/priest/shadow/TestShadow.results
=> Fix incorrect proc data for Heartsong and Gnomish X-Ray enchants

sim/common/cata/stat_bonus_cds.go, sim/death_knight/blood/TestBlood.results, sim/death_knight/frost/TestFrost.results, sim/druid/feral/TestFeral.results, sim/druid/guardian/TestGuardian.results, sim/hunter/beast_mastery/TestBM.results, sim/hunter/marksmanship/TestMM.results, sim/mage/arcane/TestArcane.results, sim/paladin/retribution/TestRetribution.results, sim/shaman/elemental/TestElemental.results, sim/warlock/affliction/TestAffliction.results, sim/warlock/demonology/TestDemonology.results, sim/warlock/destruction/TestDestruction.results, sim/warrior/arms/TestArms.results
Fixed CD details for Fire of the Deep, Vicious Gladiator's Emblem of Cruelty, and Vicious Gladiator's Emblem of Tenacity.
On branch bugfix/fix-trinkets
modified:   sim/common/cata/stat_bonus_cds.go
modified:   sim/death_knight/blood/TestBlood.results
modified:   sim/death_knight/frost/TestFrost.results
modified:   sim/druid/guardian/TestGuardian.results
modified:   sim/hunter/marksmanship/TestMM.results
modified:   sim/mage/arcane/TestArcane.results
modified:   sim/paladin/retribution/TestRetribution.results
modified:   sim/shaman/elemental/TestElemental.results
modified:   sim/warlock/affliction/TestAffliction.results
modified: …
=> More trinket fixes
